In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
arr1=np.array(['abc',1,3.9])
ser=pd.Series(['abc',1,3.9])
for i in arr1:
    print(i.dtype)
for i in ser:
    print(i,type(i))

<U3
<U1
<U3
abc <class 'str'>
1 <class 'int'>
3.9 <class 'float'>

In [4]:
arr=np.random.randint(15,30,20)
ser=pd.Series(arr,name='age')
print(ser)

0     28
1     22
2     16
3     21
4     17
5     24
6     17
7     27
8     28
9     26
10    20
11    25
12    21
13    28
14    27
15    15
16    28
17    26
18    22
19    29
Name: age, dtype: int32

In [5]:
ser[0::2]

0     28
2     16
4     17
6     17
8     28
10    20
12    21
14    27
16    28
18    22
Name: age, dtype: int32

In [6]:
arr=pd.Series(np.random.randint(15,30,5),name='age',index=['a','b','c','d','e'])
print(arr)

a    19
b    16
c    22
d    16
e    22
Name: age, dtype: int32

In [7]:
arr=pd.Series(np.random.randint(0,10,10),name='nums',index=[chr(ord('A')+i) for i in range(10)])
arr

A    0
B    7
C    3
D    4
E    7
F    7
G    4
H    6
I    8
J    8
Name: nums, dtype: int32

In [8]:
f_col=np.random.randint(1,20,10)
s_col=np.random.choice(['M','F'],10)

In [9]:
ages=pd.Series(f_col,name='age')
genders=pd.Series(s_col,name='genders')

In [10]:
arr=pd.concat((ages,genders),axis=1)

In [11]:
arr.values

array([[1, 'F'],
       [16, 'F'],
       [14, 'M'],
       [19, 'M'],
       [1, 'F'],
       [9, 'M'],
       [6, 'M'],
       [2, 'M'],
       [10, 'M'],
       [5, 'F']], dtype=object)

In [12]:
ages.index

RangeIndex(start=0, stop=10, step=1)

In [13]:
genders.index

RangeIndex(start=0, stop=10, step=1)

In [14]:
arr.index

RangeIndex(start=0, stop=10, step=1)

In [15]:
print(arr)

   age genders
0    1       F
1   16       F
2   14       M
3   19       M
4    1       F
5    9       M
6    6       M
7    2       M
8   10       M
9    5       F

In [27]:
print(arr.dtype)

int64

In [28]:
arr=arr.astype(np.int8)

In [29]:
print(arr.dtype)

int8

In [30]:
arr=pd.Series(np.random.randint(10,50,100000),name='data')
print(arr.dtype)
print(arr.nbytes)

int32
400000

In [31]:
arr1=arr.astype(np.int8)

In [32]:
print(arr1.dtype)

int8

In [33]:
print(arr1.nbytes)

100000

In [34]:
path=r'C:\Users\masir\OneDrive\Desktop\file'
arr.to_csv(path+'/'+'int32.csv')

In [35]:
path=r'C:\Users\masir\OneDrive\Desktop\file'
arr1.to_csv(path+'/'+'int8.csv')

In [36]:
path=r'C:\Users\masir\OneDrive\Desktop\file'
arr.to_csv(path+'/'+'int32.pkl')
path=r'C:\Users\masir\OneDrive\Desktop\file'
arr1.to_csv(path+'/'+'int8.pkl')

In [37]:
pd.Series([1,2,3,4]).is_monotonic_increasing

True

In [38]:
pd.Series([1,2,3,4,2]).is_monotonic_increasing

False

In [39]:
pd.Series([1,2,3,4]).is_monotonic_decreasing

False

In [40]:
pd.Series([4,3,2,1]).is_monotonic_decreasing

True

In [41]:
pd.Series([4,3,2,1,1]).unique()

array([4, 3, 2, 1], dtype=int64)

In [42]:
arr=pd.Series([1,2,np.nan,None,''])
print(arr)

0       1
1       2
2     NaN
3    None
4
dtype: object

In [43]:
arr1=arr.dropna()
print(arr)
print(arr1)

0       1
1       2
2     NaN
3    None
4
dtype: object
0    1
1    2
4
dtype: object

In [44]:
arr.dropna(inplace=True)

In [45]:
arr

0    1
1    2
4
dtype: object

In [46]:
arr=pd.Series([1,2,np.nan,None,''])
arr.fillna(10,inplace=True)
print(arr)

0     1
1     2
2    10
3    10
4
dtype: object

In [47]:
arr.replace('','abc')

0      1
1      2
2     10
3     10
4    abc
dtype: object

In [48]:
arr=pd.Series([1,2,3,4,2])
arr.clip(2,3,inplace=True)

In [49]:
arr

0    2
1    2
2    3
3    3
4    2
dtype: int64

In [50]:
arr = pd.Series([1, 2, 3, 'a'])
arr = pd.to_numeric(arr, errors='coerce').astype(np.int8, errors='ignore')
print(arr)

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [51]:
df = pd.DataFrame({
    'Name': ['A', 'B', 'C','D'],
    'Age': [20, 25, 30,np.nan],
    'Score': [88.5, 92.3, 85.0,95.0]
}) 
print(df.dtypes)

Name      object
Age      float64
Score    float64
dtype: object

In [52]:
df=df.convert_dtypes()

In [53]:
print(df.dtypes)

Name     string[python]
Age               Int64
Score           Float64
dtype: object

In [54]:
print(df)

  Name   Age  Score
0    A    20   88.5
1    B    25   92.3
2    C    30   85.0
3    D  <NA>   95.0

In [55]:
df['Age'].astype(np.float64).dtype

dtype('float64')

In [56]:
arr1 = pd.Series(["male","male","female","female"],name="gender")

In [57]:
arr1.describe()

count        4
unique       2
top       male
freq         2
Name: gender, dtype: object

In [58]:
arr=np.arange(9).reshape(3,3)
arr1=pd.DataFrame(arr,columns=['col1', 'col2', 'col3'])
arr1

   col1  col2  col3
0     0     1     2
1     3     4     5
2     6     7     8

In [59]:
arr1.columns=['c1','c2','c3']

In [60]:
arr1

   c1  c2  c3
0   0   1   2
1   3   4   5
2   6   7   8

In [61]:
import requests

In [62]:
data=requests.get('https://randomuser.me/api/')
print(data)

<Response [200]>

In [63]:
d={'names':[],'genders':[],'ages':[],'countrys':[],'states':[],'lattitudes':[],'longitudes':[]}
while len(d['names'])<=1000:
    data=requests.get('https://randomuser.me/api/')
    if data.status_code == 200:
        try:
            json_data=data.json()
            named=json_data['results'][0]['name'] 
            name=f'{named['title']} {named['first']} {named['last']}'
            d['names'].append(name)
            gender=json_data['results'][0]['gender']
            d['genders'].append(gender)
            age=json_data['results'][0]['dob']['age']
            d['ages'].append(age)
            country=json_data['results'][0]['location']['country']
            d['countrys'].append(country)
            state=json_data['results'][0]['location']['state']
            d['states'].append(state)
            lattitude=json_data['results'][0]['location']['coordinates']['latitude']
            d['lattitudes'].append(lattitude)
            longtitude=json_data['results'][0]['location']['coordinates']['longitude']
            d['longitudes'].append(lattitude)
        except IndexError:
            continue

In [ ]:
d['names']

In [65]:

df = pd.DataFrame({
    'Roll': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = df.set_index(['Roll','Name'])
print(df2)

Empty DataFrame
Columns: []
Index: [(1, Alice), (2, Bob), (3, Charlie)]

In [41]:
df=pd.read_csv(r"C:\Users\masir\Downloads\Titanic-Dataset.csv")

In [42]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [16]:
df.iloc[886,3]

'Montvila, Rev. Juozas'

In [17]:
df.shape

(891, 12)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [38]:
df[df['Sex'] == 'male']

     Age   Sex  Survived
0   22.0  male         0
4   35.0  male         0
5    NaN  male         0
6   54.0  male         0
7    2.0  male         0
12  20.0  male         0
13  39.0  male         0
16   2.0  male         0
17   NaN  male         1
20  35.0  male         0

In [44]:
d1 = {"id":[123,456],
      "name":["charan","sudhir"],
      "gender":["male","male"]}

d2 = {"id":[123,456],
      "mother_name":["mom1","mom2"],
      "father_name":["dad1","dad2"]}


d3 = {"id":[123,456],
      "address":["hyd","bng"]}

d1 = pd.DataFrame(d1)
d2 = pd.DataFrame(d2)
d3 = pd.DataFrame(d3)

In [45]:
d1

    id    name gender
0  123  charan   male
1  456  sudhir   male

In [46]:
d2

    id mother_name father_name
0  123        mom1        dad1
1  456        mom2        dad2

In [47]:
d3

    id address
0  123     hyd
1  456     bng

In [50]:
pd.concat((d1,d2,d3),axis=1)

    id    name gender   id mother_name father_name   id address
0  123  charan   male  123        mom1        dad1  123     hyd
1  456  sudhir   male  456        mom2        dad2  456     bng

In [55]:
d1[d1['id']==123]

    id    name gender
0  123  charan   male

In [3]:
import pandas as pd

In [5]:
arr=pd.Series([1,2,3],index=['A','B','C'],name='indexs')

In [6]:
arr

A    1
B    2
C    3
Name: indexs, dtype: int64

In [8]:
data=pd.Series(100,index=[1,2,3,4])

In [9]:
data

1    100
2    100
3    100
4    100
dtype: int64

In [10]:
s2 = pd.Series(
    data={'Math': 95, 'Science': 88, 'English': 92},
    dtype='float64',
    name='Marks'
)
print(s2)

Math       95.0
Science    88.0
English    92.0
Name: Marks, dtype: float64

In [3]:
import pandas as pd
import numpy as np

In [10]:
arr1=pd.Series(np.random.randint(1000,5000,9),name='col2')
arr2=pd.Series(np.random.randint(10,50,15),name='col2')
arr3=pd.Series(np.random.randint(10,100,20),name='col3')
df=pd.concat([arr1,arr2,arr3],axis=1)
df

      col2  col2  col3
0   4852.0  32.0    52
1   2362.0  23.0    63
2   4189.0  43.0    51
3   4773.0  32.0    30
4   3705.0  28.0    78
5   1714.0  26.0    81
6   1823.0  32.0    93
7   1485.0  40.0    40
8   3641.0  31.0    23
9      NaN  19.0    29
10     NaN  45.0    26
11     NaN  41.0    61
12     NaN  10.0    12
13     NaN  38.0    46
14     NaN  49.0    16
15     NaN   NaN    35
16     NaN   NaN    92
17     NaN   NaN    73
18     NaN   NaN    12
19     NaN   NaN    95

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col2    9 non-null      float64
 1   col2    15 non-null     float64
 2   col3    20 non-null     int32
dtypes: float64(2), int32(1)
memory usage: 532.0 bytes

In [14]:
df.isna().sum()

col2    11
col2     5
col3     0
dtype: int64

In [16]:
df.notnull().sum()

col2     9
col2    15
col3    20
dtype: int64

In [17]:
df.dropna(inplace=True)

In [18]:
df

     col2  col2  col3
0  4852.0  32.0    52
1  2362.0  23.0    63
2  4189.0  43.0    51
3  4773.0  32.0    30
4  3705.0  28.0    78
5  1714.0  26.0    81
6  1823.0  32.0    93
7  1485.0  40.0    40
8  3641.0  31.0    23

In [23]:
arr1=pd.Series(np.random.randint(1000,5000,9),name='col1')
arr2=pd.Series(np.random.randint(10,50,15),name='col2')
arr3=pd.Series(np.random.randint(10,100,20),name='col3')
df=pd.concat([arr1,arr2,arr3],axis=1)
df

      col1  col2  col3
0   4383.0  34.0    42
1   3054.0  47.0    38
2   1216.0  32.0    33
3   1271.0  26.0    62
4   1904.0  25.0    97
5   1488.0  45.0    82
6   2258.0  24.0    80
7   4331.0  23.0    82
8   1266.0  23.0    65
9      NaN  38.0    18
10     NaN  29.0    31
11     NaN  47.0    68
12     NaN  49.0    48
13     NaN  38.0    33
14     NaN  29.0    20
15     NaN   NaN    67
16     NaN   NaN    83
17     NaN   NaN    63
18     NaN   NaN    28
19     NaN   NaN    68

In [28]:
df['col2'].fillna(df['col2'].notnull().mean(),inplace=True)

C:\Users\masir\AppData\Local\Temp\ipykernel_10320\785071004.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['col2'].fillna(df['col2'].notnull().mean(),inplace=True)

In [34]:
df['col1'].fillna(df['col1'].notnull().sum(),inplace=True)

C:\Users\masir\AppData\Local\Temp\ipykernel_10320\2283221579.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['col1'].fillna(df['col1'].notnull().sum(),inplace=True)

In [30]:
df['col1'].mode()

0    1216.0
1    1266.0
2    1271.0
3    1488.0
4    1904.0
5    2258.0
6    3054.0
7    4331.0
8    4383.0
Name: col1, dtype: float64

In [31]:
type(df)

pandas.core.frame.DataFrame

In [35]:
arr1=pd.Series(np.random.randint(1000,5000,9),name='col1')
arr2=pd.Series(np.random.randint(10,50,15),name='col2')
arr3=pd.Series(np.random.randint(10,100,20),name='col3')
df=pd.concat([arr1,arr2,arr3],axis=1)
dfarr1=pd.Series

      col1  col2  col3
0   1910.0  13.0    41
1   2086.0  28.0    77
2   2144.0  34.0    23
3   4622.0  23.0    88
4   1567.0  18.0    68
5   1869.0  15.0    77
6   4556.0  23.0    85
7   2050.0  43.0    58
8   3582.0  21.0    94
9      NaN  38.0    86
10     NaN  26.0    29
11     NaN  38.0    46
12     NaN  45.0    60
13     NaN  31.0    18
14     NaN  47.0    93
15     NaN   NaN    24
16     NaN   NaN    73
17     NaN   NaN    97
18     NaN   NaN    38
19     NaN   NaN    49

In [36]:
df['col1'].mean()

2709.5555555555557

In [42]:
df[df['col1'].notnull()]['col1'].mean()

2709.5555555555557

In [ ]:
df1=pd.Series(np.array(np.random.randint(10000,50000,10)),name='Husband_Income')
df2=pd.Series(np.array(np.random.randint(10000,50000,10)),name='Wife_Income')
df=pd.compat

In [43]:
arr1 = pd.Series(["Karri SaiCharan","Kavala SaiSudhir","Bindella RakeshReddy"],name="name")
df = pd.DataFrame(arr1)

In [44]:
df

                   name
0       Karri SaiCharan
1      Kavala SaiSudhir
2  Bindella RakeshReddy

In [52]:
fname,lname=df.loc[0,'name'].split()

In [49]:
print(fname,lname)

Karri SaiCharan

In [53]:
type(fname)

str

In [95]:
arr=df.loc[0].str.split()
arr

name     [Karri, SaiCharan]
first               [Karri]
last            [SaiCharan]
Name: 0, dtype: object

In [87]:
words = arr.iloc[0]

In [88]:
fname,lname=words

In [89]:
fname,lname

('Karri', 'SaiCharan')

In [90]:
df[['first', 'last']] = df['name'].str.split(n=1, expand=True)

In [91]:
df

                   name     first         last
0       Karri SaiCharan     Karri    SaiCharan
1      Kavala SaiSudhir    Kavala    SaiSudhir
2  Bindella RakeshReddy  Bindella  RakeshReddy

In [93]:
df

                   name     first         last
0       Karri SaiCharan     Karri    SaiCharan
1      Kavala SaiSudhir    Kavala    SaiSudhir
2  Bindella RakeshReddy  Bindella  RakeshReddy

In [94]:
df.loc[0]

name     Karri SaiCharan
first              Karri
last           SaiCharan
Name: 0, dtype: object

In [97]:
arr1 = pd.Series(["Karri SaiCharan","Kavala SaiSudhir","Bindella RakeshReddy"], name="name")
df = pd.DataFrame(arr1)

In [98]:
df

                   name
0       Karri SaiCharan
1      Kavala SaiSudhir
2  Bindella RakeshReddy

In [105]:
import os
folder_path=r'C:\Users\masir\Downloads\eda_images'

In [107]:

paths=[]
names=[]
for file in os.listdir(folder_path):
    paths.append(folder_path+'/'+file)
    names.append(file.split('.')[0])

In [118]:
arr1 = pd.Series(paths,  name='filepath')
arr2 = pd.Series(names,  name='filename')

In [128]:
df=pd.concat([arr1,arr2],axis=1)

In [129]:
df

                                            filepath             filename
0    C:\Users\masir\Downloads\eda_images/images.jpeg               images
1       C:\Users\masir\Downloads\eda_images/lp3.jpeg                  lp3
2   C:\Users\masir\Downloads\eda_images/prabhas.jpeg              prabhas
3  C:\Users\masir\Downloads\eda_images/scorpion a...  scorpion and spider
4  C:\Users\masir\Downloads\eda_images/scorpion.jpeg             scorpion
5    C:\Users\masir\Downloads\eda_images/spider.jpeg               spider

In [130]:
df['array']=df['filepath'].apply(lambda filepath:cv2.imread(filepath))

In [131]:
df

,filepath,filename,array
0,C:\Users\masir\Downloads\eda_images/images.jpeg,images,"[[[109, 128, 149], [111, 128, 147], [112, 128,..."
1,C:\Users\masir\Downloads\eda_images/lp3.jpeg,lp3,"[[[0, 0, 0], [31, 31, 31], [25, 25, 25], [23, ..."
2,C:\Users\masir\Downloads\eda_images/prabhas.jpeg,prabhas,"[[[29, 37, 26], [28, 36, 25], [26, 34, 23], [2..."
3,C:\Users\masir\Downloads\eda_images/scorpion a...,scorpion and spider,"[[[167, 189, 225], [163, 185, 221], [155, 178,..."
4,C:\Users\masir\Downloads\eda_images/scorpion.jpeg,scorpion,"[[[79, 123, 122], [80, 124, 123], [83, 127, 12..."
5,C:\Users\masir\Downloads\eda_images/spider.jpeg,spider,"[[[255, 255, 254], [255, 255, 254], [255, 255,..."

In [132]:
df['height']=df['array'].apply(lambda x:x.shape)

In [133]:
df

,filepath,filename,array,height
0,C:\Users\masir\Downloads\eda_images/images.jpeg,images,"[[[109, 128, 149], [111, 128, 147], [112, 128,...","(187, 270, 3)"
1,C:\Users\masir\Downloads\eda_images/lp3.jpeg,lp3,"[[[0, 0, 0], [31, 31, 31], [25, 25, 25], [23, ...","(169, 297, 3)"
2,C:\Users\masir\Downloads\eda_images/prabhas.jpeg,prabhas,"[[[29, 37, 26], [28, 36, 25], [26, 34, 23], [2...","(194, 259, 3)"
3,C:\Users\masir\Downloads\eda_images/scorpion a...,scorpion and spider,"[[[167, 189, 225], [163, 185, 221], [155, 178,...","(168, 300, 3)"
4,C:\Users\masir\Downloads\eda_images/scorpion.jpeg,scorpion,"[[[79, 123, 122], [80, 124, 123], [83, 127, 12...","(170, 297, 3)"
5,C:\Users\masir\Downloads\eda_images/spider.jpeg,spider,"[[[255, 255, 254], [255, 255, 254], [255, 255,...","(189, 266, 3)"

In [136]:
df['weight']=df['array'].apply(lambda x:x.shape)

In [137]:
df

,filepath,filename,array,height,weight
0,C:\Users\masir\Downloads\eda_images/images.jpeg,images,"[[[109, 128, 149], [111, 128, 147], [112, 128,...","(187, 270, 3)","(187, 270, 3)"
1,C:\Users\masir\Downloads\eda_images/lp3.jpeg,lp3,"[[[0, 0, 0], [31, 31, 31], [25, 25, 25], [23, ...","(169, 297, 3)","(169, 297, 3)"
2,C:\Users\masir\Downloads\eda_images/prabhas.jpeg,prabhas,"[[[29, 37, 26], [28, 36, 25], [26, 34, 23], [2...","(194, 259, 3)","(194, 259, 3)"
3,C:\Users\masir\Downloads\eda_images/scorpion a...,scorpion and spider,"[[[167, 189, 225], [163, 185, 221], [155, 178,...","(168, 300, 3)","(168, 300, 3)"
4,C:\Users\masir\Downloads\eda_images/scorpion.jpeg,scorpion,"[[[79, 123, 122], [80, 124, 123], [83, 127, 12...","(170, 297, 3)","(170, 297, 3)"
5,C:\Users\masir\Downloads\eda_images/spider.jpeg,spider,"[[[255, 255, 254], [255, 255, 254], [255, 255,...","(189, 266, 3)","(189, 266, 3)"