In [137]:
import pandas as pd
import numpy as np

# Series
##### Series	Homogeneous in storage (one dtype)
##### Iteration	Shows individual element datatypes
##### object dtype	A general “box” that can hold mixed Python objects

In [37]:
arr=np.random.randint(1,50,5)
print(arr)

[36 11 47 20 17]

In [38]:
series=pd.Series(arr)
print(series)
print(type(series))

0    36
1    11
2    47
3    20
4    17
dtype: int32
<class 'pandas.core.series.Series'>

In [39]:
series=pd.Series(arr,name='integers',index=[chr(65+i) for i in range(5)])
print(series)
print(type(series))

A    36
B    11
C    47
D    20
E    17
Name: integers, dtype: int32
<class 'pandas.core.series.Series'>

In [40]:
# Tabular Dataset -------> 2D array
# Images ----------------> 2D array or 3D array
# Text Dataset ----------> 1D array
# Audio Dataset ---------> 1D array
# Sensor Data -----------> 1D array

In [41]:
indexes = [f"a_{i}" for i in range(10)]
arr1 = pd.Series(np.random.randint(15,30,10),name="age",index=indexes)
print(arr1)

a_0    16
a_1    15
a_2    29
a_3    25
a_4    23
a_5    26
a_6    28
a_7    21
a_8    15
a_9    22
Name: age, dtype: int32

In [42]:
arr1 = pd.Series(np.random.randint(10,30,10),name="age")
arr2 = pd.Series(np.random.choice(["male","female","other"],10),name="gender")
print(arr1)
print(arr2)

0    28
1    20
2    18
3    23
4    19
5    18
6    14
7    26
8    14
9    17
Name: age, dtype: int32
0     other
1    female
2    female
3    female
4      male
5    female
6    female
7     other
8    female
9    female
Name: gender, dtype: object

In [43]:
series2 = pd.Series(
    data=100,
    index=['a', 'b', 'c', 'd'],
    dtype='int32',
    name='Constant'
)
print(s4)

a    100
b    100
c    100
d    100
Name: Constant, dtype: int32

In [44]:
arr=[1,2,3,4,5,'a',6.5]
s1=pd.Series(arr,name='list')
print(s1)

0      1
1      2
2      3
3      4
4      5
5      a
6    6.5
Name: list, dtype: object

In [45]:
print(s1.map(type)) #heterogenous

0      <class 'int'>
1      <class 'int'>
2      <class 'int'>
3      <class 'int'>
4      <class 'int'>
5      <class 'str'>
6    <class 'float'>
Name: list, dtype: object

In [46]:
s2 = pd.Series(
    data={'Math': 95, 'Science': 88, 'English': 92},
    index=['Math', 'Science', 'English'],
    dtype='float64',
    name='Marks'
)
print(s2)

Math       95.0
Science    88.0
English    92.0
Name: Marks, dtype: float64

In [47]:
marks = pd.Series(
    data={'Math': 90, 'Science': 85, 'English': 70, 'History': 60},
    index=['Math', 'Science', 'English', 'History'],
    dtype='int64',
    name='Exam Marks'
)
marks_with_bonus = marks + 5
high_scores = marks_with_bonus[marks_with_bonus > 75]
print("Original Marks:\n", marks)
print("\nWith Bonus:\n", marks_with_bonus)
print("\nHigh Scorers:\n", high_scores)

Original Marks:
 Math       90
Science    85
English    70
History    60
Name: Exam Marks, dtype: int64

With Bonus:
 Math       95
Science    90
English    75
History    65
Name: Exam Marks, dtype: int64

High Scorers:
 Math       95
Science    90
Name: Exam Marks, dtype: int64

# DataFrame()

In [5]:
data={
    'Name':['Alice','Bob','Charlie'],
    'Age':[25,27,29],
    'city':['Hyd','Banglore','Chennai']
}
df=pd.DataFrame(data,index=[f'row_{i}' for i in range(len(data))])
print(df)

          Name  Age      city
row_0    Alice   25       Hyd
row_1      Bob   27  Banglore
row_2  Charlie   29   Chennai

In [10]:
data=[['Alice',25,'New York'],['Bob',30,'London'],['Charlie',22,'Paris']]
df=pd.DataFrame(data)
df

         0   1         2
0    Alice  25  New York
1      Bob  30    London
2  Charlie  22     Paris

In [11]:
df.columns=['name','age','city']
df.index=['r1','r2','r3']
df

       name  age      city
r1    Alice   25  New York
r2      Bob   30    London
r3  Charlie   22     Paris

In [12]:
data=[{'name':'Alice','Age':25,'City':'Mumbai'},
      {'name':'Bob','Age':20,'City':'Kolkata'},
     {'name':'Charlie','Age':22,'City':'Pune'}]
df=pd.DataFrame(data)
print(df)

      name  Age     City
0    Alice   25   Mumbai
1      Bob   20  Kolkata
2  Charlie   22     Pune

In [13]:
data=[{'name':'Alice','Age':25},
      {'name':'Bob','Age':20,'City':'Kolkata'},
     {'name':'Charlie'}]
df=pd.DataFrame(data)
print(df)

      name   Age     City
0    Alice  25.0      NaN
1      Bob  20.0  Kolkata
2  Charlie   NaN      NaN

In [14]:
data=pd.DataFrame([[10,20],[30,40]],index=['r1','r2'],columns=['marks','Score'],dtype=float,copy=True)
print(data)

    marks  Score
r1   10.0   20.0
r2   30.0   40.0

In [15]:
import pandas as pd

data = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
df = pd.DataFrame(data, columns=['Math', 'Science', 'English'])
print(df)

   Math  Science  English
0    10       20       30
1    40       50       60
2    70       80       90

In [16]:
import pandas as pd

data = {
    'Marks': pd.Series([85, 90, 75], index=['A', 'B', 'C']),
    'Age': pd.Series([21, 22, 23], index=['A', 'B', 'C'])
}
df = pd.DataFrame(data)
print(df)

   Marks  Age
A     85   21
B     90   22
C     75   23

In [18]:
data = {
    'Marks': pd.Series([85, 90, 75], index=['A', 'B', 'C']),
    'Age': pd.Series([21, 22, 23], index=['D', 'E', 'C'])
}
df = pd.DataFrame(data)
print(df)

   Marks   Age
A   85.0   NaN
B   90.0   NaN
C   75.0  23.0
D    NaN  21.0
E    NaN  22.0

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [20]:
data = ([1, 2, 3], [4, 5, 6])
df = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print(df)

   X  Y  Z
0  1  2  3
1  4  5  6

In [21]:
data = {
    'A': (10, 20, 30),
    'B': (40, 50, 60)
}
df = pd.DataFrame(data)
print(df)

    A   B
0  10  40
1  20  50
2  30  60

In [22]:
data = [(1, 'A'), (2, 'B'), (3, 'C')]
df = pd.DataFrame(data, columns=['ID', 'Letter'])
print(df)

   ID Letter
0   1      A
1   2      B
2   3      C

In [23]:
df = pd.DataFrame(columns=['Name', 'Age', 'City'])
print(df)

Empty DataFrame
Columns: [Name, Age, City]
Index: []

# Renaming columns and index

In [26]:
data=pd.DataFrame([[10,20,70],[30,40,80],[50,60,90]],index=['r1','r2','r3'],columns=['A','B','C'],dtype=float,copy=True)
print(data)

       A     B     C
r1  10.0  20.0  70.0
r2  30.0  40.0  80.0
r3  50.0  60.0  90.0

In [32]:
data.rename(columns={'A':'marks','C':'Score'},inplace=True)
print(data)

    marks     B  Score
r1   10.0  20.0   70.0
r2   30.0  40.0   80.0
r3   50.0  60.0   90.0

In [ ]:
data.rename(columns={'A':'marks','C':'Score'},inplace=True)
print(data)

In [35]:
data.rename(index={'r1':'row1','r3':'row2'},inplace=True)
print(data)

      marks     B  Score
row1   10.0  20.0   70.0
r2     30.0  40.0   80.0
row2   50.0  60.0   90.0

In [40]:
data.rename(columns={'marks':'Marks','Score':'Scores'},index={'row1':'row_1','row2':'row_2'},inplace=True)
print(data)

       Marks     B  Scores
row_1   10.0  20.0    70.0
r2      30.0  40.0    80.0
row_2   50.0  60.0    90.0

In [42]:
# all at once
data.columns=['Marks','Ages','Scores']
data.index=['row_1','row_2','row_3']
data

       Marks  Ages  Scores
row_1   10.0  20.0    70.0
row_2   30.0  40.0    80.0
row_3   50.0  60.0    90.0

# dtypes and dtype

In [33]:
marks = pd.Series(
    data={'Math': 90, 'Science': 85, 'English': 70, 'History': 60},
    index=['Math', 'Science', 'English', 'History'],
    dtype='int64',
    name='Exam Marks'
)
print(marks.dtype)

int64

In [43]:
s = pd.Series([10, 20, 30])
print(s.dtype)

int64

In [44]:
s = pd.Series([10, 20.5, 30])
print(s.dtype)

float64

In [45]:
s = pd.Series(["a", "b", "c"])
print(s.dtype)

object

In [46]:
data = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [1.1, 2.2, 3.3],
    'C': ['x', 'y', 'z']
})

print(data.dtypes)

A      int64
B    float64
C     object
dtype: object

In [36]:
df = pd.DataFrame({
    'Name': ['A', 'B', 'C'],
    'Age': [20, 25, 30],
    'Score': [88.5, 92.3, 85.0]
}) 
print(df.dtypes)

Name      object
Age        int64
Score    float64
dtype: object

# nullable data types (Int64, Float64, boolean)

In [48]:
s=pd.Series([1,2,3,np.nan])
print(s)
print(s.dtype)

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64
float64

In [49]:
s=pd.Series([1,2,3,np.nan],dtype='Int64')
print(s)
print(s.dtype)

0       1
1       2
2       3
3    <NA>
dtype: Int64
Int64

In [50]:
s = pd.Series([1.1, 2.2, pd.NA], dtype="Float64")
print(s)
print("dtype:", s.dtype)

0     1.1
1     2.2
2    <NA>
dtype: Float64
dtype: Float64

In [51]:
s = pd.Series([True, False, pd.NA], dtype="boolean")
print(s)
print("dtype:", s.dtype)

0     True
1    False
2     <NA>
dtype: boolean
dtype: boolean

In [53]:
df = pd.DataFrame({
    "age": pd.Series([25, 30, pd.NA], dtype="Int64"),
    "height": pd.Series([5.5, pd.NA, 6.1], dtype="Float64"),
    "active": pd.Series([True, pd.NA, False], dtype="boolean")
})

print(df)
print(df.dtypes)

    age  height  active
0    25     5.5    True
1    30    <NA>    <NA>
2  <NA>     6.1   False
age         Int64
height    Float64
active    boolean
dtype: object

# shape

In [54]:
import pandas as pd

df = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [40, 50, 60]
})

print(df.shape)

(3, 2)

In [56]:
s = pd.Series([1, 2, 3, 4, 5])
print(s.shape)

(5,)

# size

In [57]:

df = pd.DataFrame([[10,20],[30,40],[50,60]])
print(df.size)

6

In [58]:
df = pd.DataFrame(columns=['A','B'])
print(df.size)

0

In [59]:
df = pd.DataFrame([[1, None],[None, None]])
print(df.size)

4

In [61]:
df = pd.DataFrame([[1,2],[3,4]])
print(df.size)        
df['C'] = [5,6]
print(df.size)

4
6

In [62]:
df = pd.DataFrame({'A':[10,20,30,40],'B':[1,2,3,4]})
print(df[df['A']>25].size)

4

# ndim

In [93]:
s = pd.Series([10, 20, 30])
print(s)
print("ndim:", s.ndim)

0    10
1    20
2    30
dtype: int64
ndim: 1

In [95]:
df = pd.DataFrame({'A':[1,2,3], 'B':[4,5,6]})
print(df)
print("ndim:", df.ndim)
print(df.shape)

   A  B
0  1  4
1  2  5
2  3  6
ndim: 2
(3, 2)

In [96]:
s = pd.Series([100])
print("ndim:", s.ndim)

ndim: 1

In [98]:
df = pd.DataFrame([[999]])
print("DataFrame ndim:", df.ndim)
squeezed = df.squeeze()
print("After squeeze:", squeezed)
print(squeezed.ndim)

DataFrame ndim: 2
After squeeze: 999
0

In [100]:
arrays = [['A','A','B'], [1,2,3]]
index = pd.MultiIndex.from_arrays(arrays, names=('Group','ID'))
df = pd.DataFrame({'Marks':[90,80,70]}, index=index)
print(df)
print("ndim:", df.ndim)
print(df.shape)

          Marks
Group ID
A     1      90
      2      80
B     3      70
ndim: 2
(3, 1)

# itemsize

In [101]:
s = pd.Series([10, 20, 30])
print(s)
print("itemsize:", s.dtype.itemsize)

0    10
1    20
2    30
dtype: int64
itemsize: 8

In [102]:
s = pd.Series([1.1, 2.2, 3.3])
print("itemsize:", s.dtype.itemsize)

itemsize: 8

In [103]:
s = pd.Series([True, False, True])
print("itemsize:", s.dtype.itemsize)

itemsize: 1

In [104]:
s = pd.Series(['A', 'B', 'C'])
print("dtype:", s.dtype)
print("itemsize:", s.dtype.itemsize)

dtype: object
itemsize: 8

In [105]:
df = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [1.1, 2.2, 3.3],
    'C': [True, False, True]
})

for col in df:
    print(col, ":", df[col].dtype.itemsize)

A : 8
B : 8
C : 1

In [107]:
s = pd.Series([1, 2, None], dtype='Int64')
print("dtype:", s.dtype)
print("itemsize:", s.dtype.itemsize)

dtype: Int64
itemsize: 8

# nbytes

In [108]:
s = pd.Series([10, 20, 30])
print("nbytes:", s.nbytes)

nbytes: 24

In [109]:
s = pd.Series([1.1, 2.2, 3.3])
print("nbytes:", s.nbytes)

nbytes: 24

In [110]:
s = pd.Series([True, False, True, False])
print("nbytes:", s.nbytes)

nbytes: 4

In [112]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [1.1, 2.2, 3.3]
})
for col in df:
    print(col, ":", df[col].nbytes)

print("Total:", sum(df[col].nbytes for col in df))

A : 24
B : 24
Total: 48

# Index

In [113]:
df=pd.DataFrame({'A':[10,20,30],'B':[40,50,60]})
print(df)

    A   B
0  10  40
1  20  50
2  30  60

In [114]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [118]:
df=pd.DataFrame({'marks':[10,20,30]},index=['Alice','Bob','Charlie'])
print(df)
print(df.index)

         marks
Alice       10
Bob         20
Charlie     30
Index(['Alice', 'Bob', 'Charlie'], dtype='object')

In [119]:
df = pd.DataFrame({'A': [1, 2, 3]})
df.index = ['x', 'y', 'z']
print(df)

   A
x  1
y  2
z  3

# set_index()

In [121]:
df=pd.DataFrame({'Roll':[1,2,3],'Name':['Alice','Bob','Charlie'],'Marks':[80,90,95]})
df2=df.set_index('Roll') 
print(df2)

         Name  Marks
Roll
1       Alice     80
2         Bob     90
3     Charlie     95

In [122]:
df3=df.set_index('Roll',drop=False)
print(df3)

      Roll     Name  Marks
Roll
1        1    Alice     80
2        2      Bob     90
3        3  Charlie     95

In [124]:
df4=df.set_index(['Roll','Name'])
print(df4)

              Marks
Roll Name
1    Alice       80
2    Bob         90
3    Charlie     95

In [125]:
df4=df.set_index(['Roll','Name','Marks'])
print(df4)

Empty DataFrame
Columns: []
Index: [(1, Alice, 80), (2, Bob, 90), (3, Charlie, 95)]

# reset_index()

In [128]:
df=pd.DataFrame({'Marks':[90,85,80]},index=['A','B','C'])
print(df)
df2=df.reset_index()
print(df2)

   Marks
A     90
B     85
C     80
  index  Marks
0     A     90
1     B     85
2     C     80

In [129]:
df3 = df.reset_index(drop=True)
print(df3)

   Marks
0     90
1     85
2     80

In [131]:
arr=[['C1','C1','C2'],['A','B','C']]
index=pd.MultiIndex.from_arrays(arr,names=('Batch','Section'))
df=pd.DataFrame({'Marks':[75,85,95]},index=index)
print(df)

               Marks
Batch Section
C1    A           75
      B           85
C2    C           95

In [132]:
print(df.reset_index(level='Batch'))

        Batch  Marks
Section
A          C1     75
B          C1     85
C          C2     95

In [135]:
df_reset = df.reset_index(level=['Batch', 'Section'])
print(df_reset)

  Batch Section  Marks
0    C1       A     75
1    C1       B     85
2    C2       C     95

In [136]:
df_reset = df.reset_index(level=['Batch', 'Section'],drop=True)
print(df_reset)

   Marks
0     75
1     85
2     95

# to_csv()

In [ ]:
# CSV stands for Comma-Separated Values.
# It’s a plain text file used to store tabular data (like spreadsheets or tables).

# Each row represents a record,
# and each column is separated by a delimiter (usually a comma ,).

In [138]:
arr1 = pd.Series(np.random.randint(10,30,10),name="age")
arr2 = pd.Series(np.random.choice(["male","female","other"],10),name="gender")
print(arr1)
print(arr2)

0    25
1    23
2    21
3    13
4    26
5    17
6    14
7    20
8    21
9    25
Name: age, dtype: int32
0    female
1      male
2    female
3      male
4    female
5      male
6      male
7      male
8      male
9      male
Name: gender, dtype: object

In [143]:
path=r'C:\Users\masir\OneDrive\Desktop\File'
arr1.to_csv(path+'/' + 'age_series.csv',index=False)

In [145]:
arr1.to_csv('age.csv') # current directory

In [148]:
path=r'C:\Users\masir\OneDrive\Desktop\File\data'
arr1.to_csv(path+'/' + 'age_series.csv',index=False,sep='\t')
# subfolder -->data

# to_pickle()

In [ ]:
# A Pickle file is a binary file format used to serialize and store Python objects — meaning it saves them exactly as they are in memory.
#  Serialization = converting a Python object into a byte stream (so it can be saved to a file or sent over a network).

In [150]:
arr1 = pd.Series(np.random.randint(10,30,10),name="age") 
print(arr1)

0    22
1    23
2    21
3    25
4    27
5    11
6    10
7    19
8    23
9    22
Name: age, dtype: int32

In [153]:
path=r'C:\Users\masir\OneDrive\Desktop\File'
arr1.to_pickle(path+'/' + 'age_series.pkl')

In [156]:
arr1.to_pickle('age.pkl') # current directory

In [157]:
arr1.to_pickle(path + '/' + 'age_series_compressed.zip', compression='zip')

# astype()

In [ ]:
# Step	What happens	Effect
# arr1 = pd.Series(np.random.randint(10,30,10000))	Creates 10,000 random integers in memory (default dtype = int64)	Stored in binary
# arr2 = arr1.astype(np.int8)	Converts to 8-bit integers (saves memory in RAM)	Takes 1/8th of space in memory, not on disk
# .to_csv()	Converts all numbers to text (strings) before saving	Every number like 27 becomes '27' (2 characters)
# Disk file (.csv)	Contains plain text digits and commas/newlines	File size same regardless of dtype


 # let us create a series array with 10000 datapoints between 10,30 and then save it 
# let us convert the same array into int8 and then save it 
# and compare the memory occupied by both of the files

# what is the benifit of type casting
# memory consumption is optimized
# speed ----> execution | time taken to load the data is also less

# “Pickle is 1D array where CSV is 2D”

In [163]:
arr1 = pd.Series(np.random.randint(10,30,10000),name="age") 
arr1.to_csv(path+'/' + 'age_seriesint.csv')

In [164]:
arr2=arr1.astype(np.int8)
arr2.to_csv(path+'/' + 'age_seriesint8.csv')

In [169]:
arr1 = pd.Series(np.random.randint(10,30,10000),name="age") 
print(arr1.nbytes)
print(arr1.dtype)
arr1.to_pickle(path+'/' + 'age_seriesint.pkl')

40000
int32

In [170]:
arr2=arr1.astype(np.int8)
print(arr2.nbytes)
print(arr2.dtype)
arr2.to_pickle(path+'/' + 'age_seriesint8.pkl')

10000
int8

# How To load Data

In [171]:
df=pd.read_pickle(r"C:\Users\masir\OneDrive\Desktop\File\age_seriesint.pkl")
print(df)

0       20
1       19
2       26
3       11
4       17
        ..
9995    11
9996    15
9997    16
9998    11
9999    29
Name: age, Length: 10000, dtype: int32

In [172]:
df=pd.read_csv(r"C:\Users\masir\Downloads\student_dataset.csv")
print(df)

    StudentID  Marks  Hours_Studied  Attendance (%)  Projects_Done
0           1     86              3              51              3
1           2     49              3              77              2
2           3     95              1              72              0
3           4     55              5              86              3
4           5     58              7              81              5
..        ...    ...            ...             ...            ...
75         76     35              1              52              3
76         77     42              8              69              0
77         78     97              1              73              3
78         79     45              1              82              4
79         80     42              2              73              4

[80 rows x 5 columns]

# name

In [173]:
s=pd.Series([1,2,3],name='Numbers')
print(s)

0    1
1    2
2    3
Name: Numbers, dtype: int64

In [174]:
s.name='Scores'
print(s.name)

Scores

In [175]:
s.name=None

In [178]:
print(s.name)

None

# columns

In [180]:
s=pd.DataFrame([[10,20,30],[40,50,60]],columns=['A','B','C'])
print(s)

    A   B   C
0  10  20  30
1  40  50  60

In [181]:
s.columns=['A1','B1','C1']

In [182]:
print(s.columns)

Index(['A1', 'B1', 'C1'], dtype='object')

In [186]:
s.columns=[None,None,None]
print(s.columns)
print(s)
# This works syntactically but sets each column label to None--> Using None does NOT remove labels

Index([None, None, None], dtype='object')
   None  None  None
0    10    20    30
1    40    50    60

In [187]:
s.columns = ['', '', '']
print(s)

0  10  20  30
1  40  50  60

# Multindex

In [64]:
arrays=[['IT','IT',"HR","HR"],['John','Mary','Steve','Lucy']]
index=pd.MultiIndex.from_arrays(arrays,names=['Department','Employee'])
df=pd.DataFrame({'Salary':[60000,65000,50000,52000]},index=index)
print(df)

                     Salary
Department Employee
IT         John       60000
           Mary       65000
HR         Steve      50000
           Lucy       52000

In [65]:
arrays=[['IT','HR',"HR","HR"],['John','Mary','Steve','Lucy']]
index=pd.MultiIndex.from_arrays(arrays,names=['Department','Employee'])
df=pd.DataFrame({'Salary':[60000,65000,50000,52000]},index=index)
print(df)

                     Salary
Department Employee
IT         John       60000
HR         Mary       65000
           Steve      50000
           Lucy       52000

In [67]:
tuples = [
    ('India', 'Delhi'),
    ('India', 'Mumbai'),
    ('USA', 'New York'),
    ('USA', 'Chicago')
]

index = pd.MultiIndex.from_tuples(tuples, names=['Country', 'City'])

df = pd.DataFrame({'Population': [30, 20, 25, 15]}, index=index)
print(df)

                  Population
Country City
India   Delhi             30
        Mumbai            20
USA     New York          25
        Chicago           15

In [68]:
index = pd.MultiIndex.from_product(
    [['Class 1', 'Class 2'], ['Term 1', 'Term 2']],
    names=['Class', 'Term']
) 
df = pd.DataFrame({'Marks': [85, 88, 78, 90]}, index=index)
print(df)

                Marks
Class   Term
Class 1 Term 1     85
        Term 2     88
Class 2 Term 1     78
        Term 2     90

# to_frame() and squeeze()

In [70]:
s = pd.Series([10, 20, 30], name='marks')
df = s.to_frame() 
df

   marks
0     10
1     20
2     30

In [71]:
s = pd.Series([100, 200, 300], index=['math', 'eng', 'sci'])
df = s.to_frame(name='scores')
print(df)

      scores
math     100
eng      200
sci      300

In [72]:
s = pd.Series(['A', 'B', 'C'])
print(s.to_frame())

   0
0  A
1  B
2  C

In [73]:
s = pd.Series([25, 30, 35], index=['A', 'B', 'C'], name='Age')
df = s.to_frame()
print(df)
df['Salary'] = [50000, 60000, 70000]
print(df)

   Age
A   25
B   30
C   35
   Age  Salary
A   25   50000
B   30   60000
C   35   70000

In [75]:
index = pd.MultiIndex.from_tuples(
    [('class1', 'A'), ('class1', 'B'), ('class2', 'A')]
)
s = pd.Series([90, 85, 88], index=index, name='score')
print(s)
df = s.to_frame()
print(df)

class1  A    90
        B    85
class2  A    88
Name: score, dtype: int64
          score
class1 A     90
       B     85
class2 A     88

In [76]:
s = pd.Series({'Alice': 10, 'Bob': 20, 'Charlie': 30}, name='Marks')
df = s.to_frame().reset_index()
print(df)

     index  Marks
0    Alice     10
1      Bob     20
2  Charlie     30

In [84]:
import pandas as pd

df = pd.DataFrame([[10], [20], [30]], columns=['Marks'])
print("Original shape:", df.shape)
print(df.squeeze())
print(df.squeeze().shape)

Original shape: (3, 1)
0    10
1    20
2    30
Name: Marks, dtype: int64
(3,)

In [85]:
df = pd.DataFrame([[85, 90, 95]], columns=['Math', 'Sci', 'Eng'])
print("Original shape:", df.shape)
print(df.squeeze())

Original shape: (1, 3)
Math    85
Sci     90
Eng     95
Name: 0, dtype: int64

In [92]:
df = pd.DataFrame([999, 888], columns=['A'])
ds = df.squeeze()
ds.name = 'Integers'
print(ds)

0    999
1    888
Name: Integers, dtype: int64

# Slicing and Indexing

In [2]:
import pandas as pd

s = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'], name='Numbers')
print(s)

a    10
b    20
c    30
d    40
e    50
Name: Numbers, dtype: int64

In [49]:
print(s['a'])
print(s['b'])
print(s['c'])
print(s['d'])
print(s['e'])

10
20
30
40
50

In [50]:
print(s[['a','c','e']])

a    10
c    30
e    50
Name: Numbers, dtype: int64

In [51]:
print(s[0])     
print(s[[0, 2, 4]])

10
a    10
c    30
e    50
Name: Numbers, dtype: int64

C:\Users\masir\AppData\Local\Temp\ipykernel_23136\2933047819.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])
C:\Users\masir\AppData\Local\Temp\ipykernel_23136\2933047819.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[[0, 2, 4]])

In [52]:
print(s[0:3])

a    10
b    20
c    30
Name: Numbers, dtype: int64

In [53]:
print(s['a':'c'])

a    10
b    20
c    30
Name: Numbers, dtype: int64

In [54]:
print(s[0::2])

a    10
c    30
e    50
Name: Numbers, dtype: int64

In [55]:
print(s['a'::2])

a    10
c    30
e    50
Name: Numbers, dtype: int64

In [4]:
print(s[s>25])

c    30
d    40
e    50
Name: Numbers, dtype: int64

# values

In [10]:
s=pd.Series([1,2,3,4],name='nums')
print(s)
print(s.values)
print(type(s.values))
print((s.values).dtype)

0    1
1    2
2    3
3    4
Name: nums, dtype: int64
[1 2 3 4]
<class 'numpy.ndarray'>
int64

In [11]:
s1=pd.Series(['apple','banana','grapes'])
print(s1.values)

['apple' 'banana' 'grapes']

In [12]:
s = pd.Series([1, 2.5, 'text', True])
print(s.values)
print((s.values).dtype)

[1 2.5 'text' True]
object

In [14]:
s = pd.Series([2, 4, 6, 8])
print(np.mean(s.values))  
print(np.max(s.values))

5.0
8