In [1]:
import pandas as pd
import numpy as np

# Series
##### Series	Homogeneous in storage (one dtype)
##### Iteration	Shows individual element datatypes
##### object dtype	A general “box” that can hold mixed Python objects

In [37]:
arr=np.random.randint(1,50,5)
print(arr)

[36 11 47 20 17]

In [38]:
series=pd.Series(arr)
print(series) 
print(type(series))

0    36
1    11
2    47
3    20
4    17
dtype: int32
<class 'pandas.core.series.Series'>

In [39]:
series=pd.Series(arr,name='integers',index=[chr(65+i) for i in range(5)])
print(series)
print(type(series))

A    36
B    11
C    47
D    20
E    17
Name: integers, dtype: int32
<class 'pandas.core.series.Series'>

In [40]:
# Tabular Dataset -------> 2D array
# Images ----------------> 2D array or 3D array
# Text Dataset ----------> 1D array
# Audio Dataset ---------> 1D array
# Sensor Data -----------> 1D array

In [41]:
indexes = [f"a_{i}" for i in range(10)]
arr1 = pd.Series(np.random.randint(15,30,10),name="age",index=indexes)
print(arr1)

a_0    16
a_1    15
a_2    29
a_3    25
a_4    23
a_5    26
a_6    28
a_7    21
a_8    15
a_9    22
Name: age, dtype: int32

In [42]:
arr1 = pd.Series(np.random.randint(10,30,10),name="age")
arr2 = pd.Series(np.random.choice(["male","female","other"],10),name="gender")
print(arr1)
print(arr2)

0    28
1    20
2    18
3    23
4    19
5    18
6    14
7    26
8    14
9    17
Name: age, dtype: int32
0     other
1    female
2    female
3    female
4      male
5    female
6    female
7     other
8    female
9    female
Name: gender, dtype: object

In [43]:
series2 = pd.Series(
    data=100,
    index=['a', 'b', 'c', 'd'],
    dtype='int32',
    name='Constant'
)
print(s4)

a    100
b    100
c    100
d    100
Name: Constant, dtype: int32

In [44]:
arr=[1,2,3,4,5,'a',6.5]
s1=pd.Series(arr,name='list')
print(s1)

0      1
1      2
2      3
3      4
4      5
5      a
6    6.5
Name: list, dtype: object

In [45]:
print(s1.map(type)) #heterogenous

0      <class 'int'>
1      <class 'int'>
2      <class 'int'>
3      <class 'int'>
4      <class 'int'>
5      <class 'str'>
6    <class 'float'>
Name: list, dtype: object

In [46]:
s2 = pd.Series(
    data={'Math': 95, 'Science': 88, 'English': 92},
    index=['Math', 'Science', 'English'],
    dtype='float64',
    name='Marks'
)
print(s2)

Math       95.0
Science    88.0
English    92.0
Name: Marks, dtype: float64

In [47]:
marks = pd.Series(
    data={'Math': 90, 'Science': 85, 'English': 70, 'History': 60},
    index=['Math', 'Science', 'English', 'History'],
    dtype='int64',
    name='Exam Marks'
)
marks_with_bonus = marks + 5
high_scores = marks_with_bonus[marks_with_bonus > 75]
print("Original Marks:\n", marks)
print("\nWith Bonus:\n", marks_with_bonus)
print("\nHigh Scorers:\n", high_scores)

Original Marks:
 Math       90
Science    85
English    70
History    60
Name: Exam Marks, dtype: int64

With Bonus:
 Math       95
Science    90
English    75
History    65
Name: Exam Marks, dtype: int64

High Scorers:
 Math       95
Science    90
Name: Exam Marks, dtype: int64

# DataFrame()

In [5]:
data={
    'Name':['Alice','Bob','Charlie'],
    'Age':[25,27,29],
    'city':['Hyd','Banglore','Chennai']
}
df=pd.DataFrame(data,index=[f'row_{i}' for i in range(len(data))])
print(df)

          Name  Age      city
row_0    Alice   25       Hyd
row_1      Bob   27  Banglore
row_2  Charlie   29   Chennai

In [10]:
data=[['Alice',25,'New York'],['Bob',30,'London'],['Charlie',22,'Paris']]
df=pd.DataFrame(data)
df

         0   1         2
0    Alice  25  New York
1      Bob  30    London
2  Charlie  22     Paris

In [11]:
df.columns=['name','age','city']
df.index=['r1','r2','r3']
df

       name  age      city
r1    Alice   25  New York
r2      Bob   30    London
r3  Charlie   22     Paris

In [12]:
data=[{'name':'Alice','Age':25,'City':'Mumbai'},
      {'name':'Bob','Age':20,'City':'Kolkata'},
     {'name':'Charlie','Age':22,'City':'Pune'}]
df=pd.DataFrame(data)
print(df)

      name  Age     City
0    Alice   25   Mumbai
1      Bob   20  Kolkata
2  Charlie   22     Pune

In [13]:
data=[{'name':'Alice','Age':25},
      {'name':'Bob','Age':20,'City':'Kolkata'},
     {'name':'Charlie'}]
df=pd.DataFrame(data)
print(df)

      name   Age     City
0    Alice  25.0      NaN
1      Bob  20.0  Kolkata
2  Charlie   NaN      NaN

In [14]:
data=pd.DataFrame([[10,20],[30,40]],index=['r1','r2'],columns=['marks','Score'],dtype=float,copy=True)
print(data)

    marks  Score
r1   10.0   20.0
r2   30.0   40.0

In [15]:
import pandas as pd

data = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
df = pd.DataFrame(data, columns=['Math', 'Science', 'English'])
print(df)

   Math  Science  English
0    10       20       30
1    40       50       60
2    70       80       90

In [16]:
import pandas as pd

data = {
    'Marks': pd.Series([85, 90, 75], index=['A', 'B', 'C']),
    'Age': pd.Series([21, 22, 23], index=['A', 'B', 'C'])
}
df = pd.DataFrame(data)
print(df)

   Marks  Age
A     85   21
B     90   22
C     75   23

In [18]:
data = {
    'Marks': pd.Series([85, 90, 75], index=['A', 'B', 'C']),
    'Age': pd.Series([21, 22, 23], index=['D', 'E', 'C'])
}
df = pd.DataFrame(data)
print(df)

   Marks   Age
A   85.0   NaN
B   90.0   NaN
C   75.0  23.0
D    NaN  21.0
E    NaN  22.0

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [20]:
data = ([1, 2, 3], [4, 5, 6])
df = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print(df)

   X  Y  Z
0  1  2  3
1  4  5  6

In [21]:
data = {
    'A': (10, 20, 30),
    'B': (40, 50, 60)
}
df = pd.DataFrame(data)
print(df)

    A   B
0  10  40
1  20  50
2  30  60

In [22]:
data = [(1, 'A'), (2, 'B'), (3, 'C')]
df = pd.DataFrame(data, columns=['ID', 'Letter'])
print(df)

   ID Letter
0   1      A
1   2      B
2   3      C

In [23]:
df = pd.DataFrame(columns=['Name', 'Age', 'City'])
print(df)

Empty DataFrame
Columns: [Name, Age, City]
Index: []

# Renaming columns and index

In [26]:
data=pd.DataFrame([[10,20,70],[30,40,80],[50,60,90]],index=['r1','r2','r3'],columns=['A','B','C'],dtype=float,copy=True)
print(data)

       A     B     C
r1  10.0  20.0  70.0
r2  30.0  40.0  80.0
r3  50.0  60.0  90.0

In [32]:
data.rename(columns={'A':'marks','C':'Score'},inplace=True)
print(data)

    marks     B  Score
r1   10.0  20.0   70.0
r2   30.0  40.0   80.0
r3   50.0  60.0   90.0

In [ ]:
data.rename(columns={'A':'marks','C':'Score'},inplace=True)
print(data)

In [35]:
data.rename(index={'r1':'row1','r3':'row2'},inplace=True)
print(data)

      marks     B  Score
row1   10.0  20.0   70.0
r2     30.0  40.0   80.0
row2   50.0  60.0   90.0

In [40]:
data.rename(columns={'marks':'Marks','Score':'Scores'},index={'row1':'row_1','row2':'row_2'},inplace=True)
print(data)

       Marks     B  Scores
row_1   10.0  20.0    70.0
r2      30.0  40.0    80.0
row_2   50.0  60.0    90.0

In [42]:
# all at once
data.columns=['Marks','Ages','Scores']
data.index=['row_1','row_2','row_3']
data

       Marks  Ages  Scores
row_1   10.0  20.0    70.0
row_2   30.0  40.0    80.0
row_3   50.0  60.0    90.0

# dtypes and dtype

In [33]:
marks = pd.Series(
    data={'Math': 90, 'Science': 85, 'English': 70, 'History': 60},
    index=['Math', 'Science', 'English', 'History'],
    dtype='int64',
    name='Exam Marks'
)
print(marks.dtype)

int64

In [43]:
s = pd.Series([10, 20, 30])
print(s.dtype)

int64

In [44]:
s = pd.Series([10, 20.5, 30])
print(s.dtype)

float64

In [2]:
s = pd.Series(["a", "b", "c"])
print(s.dtypes)

object

In [46]:
data = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [1.1, 2.2, 3.3],
    'C': ['x', 'y', 'z']
})

print(data.dtypes)

A      int64
B    float64
C     object
dtype: object

In [36]:
df = pd.DataFrame({
    'Name': ['A', 'B', 'C'],
    'Age': [20, 25, 30],
    'Score': [88.5, 92.3, 85.0]
}) 
print(df.dtypes)

Name      object
Age        int64
Score    float64
dtype: object

# nullable data types (Int64, Float64, boolean)

In [48]:
s=pd.Series([1,2,3,np.nan])
print(s)
print(s.dtype)

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64
float64

In [49]:
s=pd.Series([1,2,3,np.nan],dtype='Int64')
print(s)
print(s.dtype)

0       1
1       2
2       3
3    <NA>
dtype: Int64
Int64

In [50]:
s = pd.Series([1.1, 2.2, pd.NA], dtype="Float64")
print(s)
print("dtype:", s.dtype)

0     1.1
1     2.2
2    <NA>
dtype: Float64
dtype: Float64

In [51]:
s = pd.Series([True, False, pd.NA], dtype="boolean")
print(s)
print("dtype:", s.dtype)

0     True
1    False
2     <NA>
dtype: boolean
dtype: boolean

In [53]:
df = pd.DataFrame({
    "age": pd.Series([25, 30, pd.NA], dtype="Int64"),
    "height": pd.Series([5.5, pd.NA, 6.1], dtype="Float64"),
    "active": pd.Series([True, pd.NA, False], dtype="boolean")
})

print(df)
print(df.dtypes)

    age  height  active
0    25     5.5    True
1    30    <NA>    <NA>
2  <NA>     6.1   False
age         Int64
height    Float64
active    boolean
dtype: object

# shape

In [54]:
import pandas as pd

df = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [40, 50, 60]
})

print(df.shape)

(3, 2)

In [56]:
s = pd.Series([1, 2, 3, 4, 5])
print(s.shape)

(5,)

# size

In [57]:

df = pd.DataFrame([[10,20],[30,40],[50,60]])
print(df.size)

6

In [58]:
df = pd.DataFrame(columns=['A','B'])
print(df.size)

0

In [59]:
df = pd.DataFrame([[1, None],[None, None]])
print(df.size)

4

In [61]:
df = pd.DataFrame([[1,2],[3,4]])
print(df.size)        
df['C'] = [5,6]
print(df.size)

4
6

In [3]:
df = pd.DataFrame({'A':[10,20,30,40],'B':[1,2,3,4]})
print(df[df['A']>25].size)

4

# ndim

In [93]:
s = pd.Series([10, 20, 30])
print(s)
print("ndim:", s.ndim)

0    10
1    20
2    30
dtype: int64
ndim: 1

In [95]:
df = pd.DataFrame({'A':[1,2,3], 'B':[4,5,6]})
print(df)
print("ndim:", df.ndim)
print(df.shape)

   A  B
0  1  4
1  2  5
2  3  6
ndim: 2
(3, 2)

In [96]:
s = pd.Series([100])
print("ndim:", s.ndim)

ndim: 1

In [98]:
df = pd.DataFrame([[999]])
print("DataFrame ndim:", df.ndim)
squeezed = df.squeeze()
print("After squeeze:", squeezed)
print(squeezed.ndim)

DataFrame ndim: 2
After squeeze: 999
0

In [100]:
arrays = [['A','A','B'], [1,2,3]]
index = pd.MultiIndex.from_arrays(arrays, names=('Group','ID'))
df = pd.DataFrame({'Marks':[90,80,70]}, index=index)
print(df)
print("ndim:", df.ndim)
print(df.shape)

          Marks
Group ID
A     1      90
      2      80
B     3      70
ndim: 2
(3, 1)

# itemsize

In [101]:
s = pd.Series([10, 20, 30])
print(s)
print("itemsize:", s.dtype.itemsize)

0    10
1    20
2    30
dtype: int64
itemsize: 8

In [102]:
s = pd.Series([1.1, 2.2, 3.3])
print("itemsize:", s.dtype.itemsize)

itemsize: 8

In [103]:
s = pd.Series([True, False, True])
print("itemsize:", s.dtype.itemsize)

itemsize: 1

In [104]:
s = pd.Series(['A', 'B', 'C'])
print("dtype:", s.dtype)
print("itemsize:", s.dtype.itemsize)

dtype: object
itemsize: 8

In [105]:
df = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [1.1, 2.2, 3.3],
    'C': [True, False, True]
})

for col in df:
    print(col, ":", df[col].dtype.itemsize)

A : 8
B : 8
C : 1

In [107]:
s = pd.Series([1, 2, None], dtype='Int64')
print("dtype:", s.dtype)
print("itemsize:", s.dtype.itemsize)

dtype: Int64
itemsize: 8

# nbytes

In [108]:
s = pd.Series([10, 20, 30])
print("nbytes:", s.nbytes)

nbytes: 24

In [109]:
s = pd.Series([1.1, 2.2, 3.3])
print("nbytes:", s.nbytes)

nbytes: 24

In [110]:
s = pd.Series([True, False, True, False])
print("nbytes:", s.nbytes)

nbytes: 4

In [112]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [1.1, 2.2, 3.3]
})
for col in df:
    print(col, ":", df[col].nbytes)

print("Total:", sum(df[col].nbytes for col in df))

A : 24
B : 24
Total: 48

# Index

In [113]:
df=pd.DataFrame({'A':[10,20,30],'B':[40,50,60]})
print(df)

    A   B
0  10  40
1  20  50
2  30  60

In [114]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [118]:
df=pd.DataFrame({'marks':[10,20,30]},index=['Alice','Bob','Charlie'])
print(df)
print(df.index)

         marks
Alice       10
Bob         20
Charlie     30
Index(['Alice', 'Bob', 'Charlie'], dtype='object')

In [119]:
df = pd.DataFrame({'A': [1, 2, 3]})
df.index = ['x', 'y', 'z']
print(df)

   A
x  1
y  2
z  3

# set_index()

In [5]:
df=pd.DataFrame({'Roll':[1,2,3],'Name':['Alice','Bob','Charlie'],'Marks':[80,90,95]})
df2=df.set_index('Roll') 
print(df2)

         Name  Marks
Roll
1       Alice     80
2         Bob     90
3     Charlie     95

In [122]:
df3=df.set_index('Roll',drop=False)
print(df3)

      Roll     Name  Marks
Roll
1        1    Alice     80
2        2      Bob     90
3        3  Charlie     95

In [124]:
df4=df.set_index(['Roll','Name'])
print(df4)

              Marks
Roll Name
1    Alice       80
2    Bob         90
3    Charlie     95

In [125]:
df4=df.set_index(['Roll','Name','Marks'])
print(df4)

Empty DataFrame
Columns: []
Index: [(1, Alice, 80), (2, Bob, 90), (3, Charlie, 95)]

In [6]:
df.set_index('Roll',inplace=True)

In [7]:
print(df)

         Name  Marks
Roll
1       Alice     80
2         Bob     90
3     Charlie     95

# reset_index()

In [8]:
df=pd.DataFrame({'Marks':[90,85,80]},index=['A','B','C'])
print(df) 
df2=df.reset_index() 
print(df2)

   Marks
A     90
B     85
C     80
  index  Marks
0     A     90
1     B     85
2     C     80

In [9]:
df3 = df.reset_index(drop=True)
print(df3)

   Marks
0     90
1     85
2     80

In [10]:
arr=[['C1','C1','C2'],['A','B','C']]
index=pd.MultiIndex.from_arrays(arr,names=('Batch','Section'))
df=pd.DataFrame({'Marks':[75,85,95]},index=index)
print(df)

               Marks
Batch Section
C1    A           75
      B           85
C2    C           95

In [11]:
print(df.reset_index(level='Batch'))

        Batch  Marks
Section
A          C1     75
B          C1     85
C          C2     95

In [12]:
df_reset = df.reset_index(level=['Batch', 'Section'])
print(df_reset)

  Batch Section  Marks
0    C1       A     75
1    C1       B     85
2    C2       C     95

In [13]:
df.reset_index(level=['Batch', 'Section'],inplace=True)

In [14]:
df

  Batch Section  Marks
0    C1       A     75
1    C1       B     85
2    C2       C     95

In [16]:
arr=[['C1','C1','C2'],['A','B','C']]
index=pd.MultiIndex.from_arrays(arr,names=('Batch','Section'))
df=pd.DataFrame({'Marks':[75,85,95]},index=index)
df_reset = df.reset_index(level=['Batch', 'Section'],drop=True)
print(df_reset)

   Marks
0     75
1     85
2     95

# to_csv()

In [ ]:
# CSV stands for Comma-Separated Values.
# It’s a plain text file used to store tabular data (like spreadsheets or tables).

# Each row represents a record,
# and each column is separated by a delimiter (usually a comma ,).

In [138]:
arr1 = pd.Series(np.random.randint(10,30,10),name="age")
arr2 = pd.Series(np.random.choice(["male","female","other"],10),name="gender")
print(arr1)
print(arr2)

0    25
1    23
2    21
3    13
4    26
5    17
6    14
7    20
8    21
9    25
Name: age, dtype: int32
0    female
1      male
2    female
3      male
4    female
5      male
6      male
7      male
8      male
9      male
Name: gender, dtype: object

In [143]:
path=r'C:\Users\masir\OneDrive\Desktop\File'
arr1.to_csv(path+'/' + 'age_series.csv',index=False)

In [145]:
arr1.to_csv('age.csv') # current directory

In [148]:
path=r'C:\Users\masir\OneDrive\Desktop\File\data'
arr1.to_csv(path+'/' + 'age_series.csv',index=False,sep='\t')
# subfolder -->data

# to_pickle()

In [ ]:
# A Pickle file is a binary file format used to serialize and store Python objects — meaning it saves them exactly as they are in memory.
#  Serialization = converting a Python object into a byte stream (so it can be saved to a file or sent over a network).

In [150]:
arr1 = pd.Series(np.random.randint(10,30,10),name="age") 
print(arr1)

0    22
1    23
2    21
3    25
4    27
5    11
6    10
7    19
8    23
9    22
Name: age, dtype: int32

In [153]:
path=r'C:\Users\masir\OneDrive\Desktop\File'
arr1.to_pickle(path+'/' + 'age_series.pkl')

In [156]:
arr1.to_pickle('age.pkl') # current directory

In [157]:
arr1.to_pickle(path + '/' + 'age_series_compressed.zip', compression='zip')

# astype()

In [ ]:
# Step	What happens	Effect
# arr1 = pd.Series(np.random.randint(10,30,10000))	Creates 10,000 random integers in memory (default dtype = int64)	Stored in binary
# arr2 = arr1.astype(np.int8)	Converts to 8-bit integers (saves memory in RAM)	Takes 1/8th of space in memory, not on disk
# .to_csv()	Converts all numbers to text (strings) before saving	Every number like 27 becomes '27' (2 characters)
# Disk file (.csv)	Contains plain text digits and commas/newlines	File size same regardless of dtype


 # let us create a series array with 10000 datapoints between 10,30 and then save it 
# let us convert the same array into int8 and then save it 
# and compare the memory occupied by both of the files

# what is the benifit of type casting
# memory consumption is optimized
# speed ----> execution | time taken to load the data is also less

# “Pickle is 1D array where CSV is 2D”

In [163]:
arr1 = pd.Series(np.random.randint(10,30,10000),name="age") 
arr1.to_csv(path+'/' + 'age_seriesint.csv')

In [164]:
arr2=arr1.astype(np.int8)
arr2.to_csv(path+'/' + 'age_seriesint8.csv')

In [169]:
arr1 = pd.Series(np.random.randint(10,30,10000),name="age") 
print(arr1.nbytes)
print(arr1.dtype)
arr1.to_pickle(path+'/' + 'age_seriesint.pkl')

40000
int32

In [170]:
arr2=arr1.astype(np.int8)
print(arr2.nbytes)
print(arr2.dtype)
arr2.to_pickle(path+'/' + 'age_seriesint8.pkl')

10000
int8

# How To load Data

In [171]:
df=pd.read_pickle(r"C:\Users\masir\OneDrive\Desktop\File\age_seriesint.pkl")
print(df)

0       20
1       19
2       26
3       11
4       17
        ..
9995    11
9996    15
9997    16
9998    11
9999    29
Name: age, Length: 10000, dtype: int32

In [172]:
df=pd.read_csv(r"C:\Users\masir\Downloads\student_dataset.csv")
print(df)

    StudentID  Marks  Hours_Studied  Attendance (%)  Projects_Done
0           1     86              3              51              3
1           2     49              3              77              2
2           3     95              1              72              0
3           4     55              5              86              3
4           5     58              7              81              5
..        ...    ...            ...             ...            ...
75         76     35              1              52              3
76         77     42              8              69              0
77         78     97              1              73              3
78         79     45              1              82              4
79         80     42              2              73              4

[80 rows x 5 columns]

# name

In [173]:
s=pd.Series([1,2,3],name='Numbers')
print(s)

0    1
1    2
2    3
Name: Numbers, dtype: int64

In [174]:
s.name='Scores'
print(s.name)

Scores

In [175]:
s.name=None

In [178]:
print(s.name)

None

# columns

In [180]:
s=pd.DataFrame([[10,20,30],[40,50,60]],columns=['A','B','C'])
print(s)

    A   B   C
0  10  20  30
1  40  50  60

In [181]:
s.columns=['A1','B1','C1']

In [182]:
print(s.columns)

Index(['A1', 'B1', 'C1'], dtype='object')

In [186]:
s.columns=[None,None,None]
print(s.columns)
print(s)
# This works syntactically but sets each column label to None--> Using None does NOT remove labels

Index([None, None, None], dtype='object')
   None  None  None
0    10    20    30
1    40    50    60

In [187]:
s.columns = ['', '', '']
print(s)

0  10  20  30
1  40  50  60

# empty

In [18]:
df=pd.DataFrame({'A':[1,2,3],
                  'B':[4,5,6]
                })
print(df)

   A  B
0  1  4
1  2  5
2  3  6

In [19]:
df.empty

False

In [20]:
df=pd.DataFrame()
df.empty

True

In [22]:
s=pd.Series()
s.empty

True

In [23]:
s=pd.Series([1,2,3])
s.empty

False

In [24]:
df = pd.DataFrame(columns=['A','B'])
print(df.empty)

True

In [26]:
df=pd.DataFrame({'A':[None, None]})
df.empty

False

In [27]:
df=pd.DataFrame({'A':[1, None]})
df.empty

False

In [28]:
df = pd.DataFrame({'A':[1,2,3]})
print(df[df['A'] > 5].empty)

True

# hasnans

In [29]:
s=pd.Series([10,None,20])
print(s.hasnans)

True

In [30]:
s=pd.Series([1,2,3])
print(s.hasnans)

False

In [31]:
s = pd.Series([5, np.nan, 7])
print(s.hasnans)

True

In [32]:
s = pd.Series([])
print(s.hasnans)

False

In [33]:
idx = pd.Index([1, 2, np.nan])
print(idx.hasnans)

True

In [34]:
df = pd.DataFrame({'A':[1, None]})
df.hasnans

AttributeError: 'DataFrame' object has no attribute 'hasnans'

In [35]:
df.isna().any().any()

True

# is_unique

In [36]:
s=pd.Series([10,20,30])
print(s.is_unique)

True

In [38]:
s=pd.Series([10,20,30,30])
print(s.is_unique)

False

In [39]:
s = pd.Series([1, np.nan, 3])
print(s.is_unique)

True

In [40]:
s = pd.Series([1, np.nan, np.nan])
print(s.is_unique)

False

In [41]:
s = pd.Series([])
print(s.is_unique)

True

In [42]:
df = pd.DataFrame({'A':[10,20,30]},
                  index=['a','b','c'])

print(df.is_unique)

AttributeError: 'DataFrame' object has no attribute 'is_unique'

In [43]:
df = pd.DataFrame({'A':[10,20,30]},
                  index=['a','b','c'])

print(df.index.is_unique)

True

In [44]:
df = pd.DataFrame({'A':[10,20,30]},
                  index=['a','a','b'])

print(df.index.is_unique)

False

# is_monotonic_increasing

In [45]:
s=pd.Series([1,2,3,4,5])
s.is_monotonic_increasing

True

In [46]:
s=pd.Series([1,2,3,4,5,5,6])
s.is_monotonic_increasing

True

In [47]:
s=pd.Series([1,2,3,8,6])
s.is_monotonic_increasing

False

In [48]:
s=pd.Series([])
s.is_monotonic_increasing

True

In [49]:
s=pd.Series([5,5,5])
s.is_monotonic_increasing

True

In [50]:
s=pd.Series([1,2,3,np.nan,4,5])
s.is_monotonic_increasing

False

# is_monotonic_decreasing

In [52]:
s = pd.Series([5, 4, 3, 2])
print(s.is_monotonic_decreasing)

True

In [53]:
s = pd.Series([5, 5, 4, 4])
print(s.is_monotonic_decreasing)

True

In [54]:
s = pd.Series([5, 3, 4])
print(s.is_monotonic_decreasing)

False

In [55]:
s = pd.Series([7, 7, 7])
print(s.is_monotonic_decreasing)

True

In [56]:
s = pd.Series([5, 4, np.nan, 2])
print(s.is_monotonic_decreasing)

False

In [310]:
df=pd.DataFrame({'A':[1,2,3]})
df.is_monotonic_decreasing

AttributeError: 'DataFrame' object has no attribute 'is_monotonic_decreasing'

In [59]:
s=pd.Series([])
s.is_monotonic_decreasing

True

# conversions

In [60]:
s = pd.Series([10, 20, 30], index=['a','b','c'])

In [308]:
df = pd.DataFrame({'A':[10,20,30], 'B':[1,2,3]}, index=['a','b','c'])

In [64]:
sdata=s.to_list()
print(sdata)
dfdata=df.to_dict('list')
print(dfdata)

[10, 20, 30]
{'A': [10, 20, 30], 'B': [1, 2, 3]}

In [65]:
sdata=s.to_dict()
print(sdata)
dfdata=df.to_dict()
print(dfdata)

{'a': 10, 'b': 20, 'c': 30}
{'A': {'a': 10, 'b': 20, 'c': 30}, 'B': {'a': 1, 'b': 2, 'c': 3}}

In [66]:
sdata=s.to_json()
print(sdata)
dfdata=df.to_json()
print(dfdata)

{"a":10,"b":20,"c":30}
{"A":{"a":10,"b":20,"c":30},"B":{"a":1,"b":2,"c":3}}

In [311]:
sdata=s.to_frame()
print(sdata)

     0
0  1.0
1  2.0
2  1.0
3  NaN

In [68]:
sdata=s.to_numpy()
print(sdata)
dfdata=df.to_numpy()
print(dfdata)

[10 20 30]
[[10  1]
 [20  2]
 [30  3]]

In [71]:
sdata=s.to_string()
print(sdata)
print(type(sdata))
dfdata=df.to_string()
print(dfdata,type(sdata))

a    10
b    20
c    30
<class 'str'>
    A  B
a  10  1
b  20  2
c  30  3 <class 'str'>

In [72]:
sdata=s.to_csv()
print(sdata)
dfdata=df.to_csv()
print(dfdata)

,0
a,10
b,20
c,30

,A,B
a,10,1
b,20,2
c,30,3

In [305]:
s.to_excel("s.xlsx")
df.to_excel("df.xlsx")
print("Series saved to s.xlsx")
print("DataFrame saved to df.xlsx")

Series saved to s.xlsx
DataFrame saved to df.xlsx

In [306]:
s.to_pickle("s.pkl")
df.to_pickle("df.pkl")
print("Pickle files saved")

Pickle files saved

In [309]:
print("Series Markdown:")
print(s.to_markdown())

print("DataFrame Markdown:")
print(df.to_markdown())
print("Markdown generated")

# Markdown is a simple way to tell the computer:
# “This is a heading”
# “This is bold”
# “This is a list”
# “This is a table”

Series Markdown:
|    |   0 |
|---:|----:|
|  0 |   1 |
|  1 |   2 |
|  2 |   1 |
|  3 | nan |
DataFrame Markdown:
|    |   A |   B |
|:---|----:|----:|
| a  |  10 |   1 |
| b  |  20 |   2 |
| c  |  30 |   3 |
Markdown generated

# Multindex

In [64]:
arrays=[['IT','IT',"HR","HR"],['John','Mary','Steve','Lucy']]
index=pd.MultiIndex.from_arrays(arrays,names=['Department','Employee'])
df=pd.DataFrame({'Salary':[60000,65000,50000,52000]},index=index)
print(df)

                     Salary
Department Employee
IT         John       60000
           Mary       65000
HR         Steve      50000
           Lucy       52000

In [65]:
arrays=[['IT','HR',"HR","HR"],['John','Mary','Steve','Lucy']]
index=pd.MultiIndex.from_arrays(arrays,names=['Department','Employee'])
df=pd.DataFrame({'Salary':[60000,65000,50000,52000]},index=index)
print(df)

                     Salary
Department Employee
IT         John       60000
HR         Mary       65000
           Steve      50000
           Lucy       52000

In [67]:
tuples = [
    ('India', 'Delhi'),
    ('India', 'Mumbai'),
    ('USA', 'New York'),
    ('USA', 'Chicago')
]

index = pd.MultiIndex.from_tuples(tuples, names=['Country', 'City'])

df = pd.DataFrame({'Population': [30, 20, 25, 15]}, index=index)
print(df)

                  Population
Country City
India   Delhi             30
        Mumbai            20
USA     New York          25
        Chicago           15

In [68]:
index = pd.MultiIndex.from_product(
    [['Class 1', 'Class 2'], ['Term 1', 'Term 2']],
    names=['Class', 'Term']
) 
df = pd.DataFrame({'Marks': [85, 88, 78, 90]}, index=index)
print(df)

                Marks
Class   Term
Class 1 Term 1     85
        Term 2     88
Class 2 Term 1     78
        Term 2     90

# unique()

In [82]:
s = pd.Series([1, 2, 2, 3, 3, 3])
print(s.unique())

[1 2 3]

In [83]:
s = pd.Series(['a', 'b', 'a', 'c'])
print(s.unique())

['a' 'b' 'c']

In [84]:
s=pd.Series([1,'1',1.0,True])
print(s.unique())

[1 '1']

In [85]:
s = pd.Series([1, 2, np.nan, None, np.nan])
print(s.unique())

[ 1.  2. nan]

In [89]:
df=pd.DataFrame({'A':[10,20,20,30],
                'B':['x','y','x','z']})
df

    A  B
0  10  x
1  20  y
2  20  x
3  30  z

In [91]:
df['A'].unique()

array([10, 20, 30], dtype=int64)

In [92]:
df['B'].unique()

array(['x', 'y', 'z'], dtype=object)

# nunique()

In [95]:
s = pd.Series([1, 1, np.nan, None, 'a', 'a'])
print(s.nunique())

2

In [96]:
s = pd.Series([1, 1, np.nan, None, 'a', 'a'])
print(s.nunique(dropna=False))

4

In [97]:
s = pd.Series([1, 1.0, True, '1'])
print(s.nunique())

2

In [98]:
df = pd.DataFrame({
    'A': [1, 1, 2],
    'B': [1, 2, 2],
    'C': [1, 1, 1]
})

print(df.nunique(axis=1))

0    1
1    2
2    2
dtype: int64

In [102]:
print(df['col'].apply(tuple).nunique())

3

# value_counts()

In [103]:
s=pd.Series([10,20,30,30])
s.value_counts()

30    2
10    1
20    1
Name: count, dtype: int64

In [104]:
s=pd.Series([1,2,1,None])
s.value_counts()

1.0    2
2.0    1
Name: count, dtype: int64

In [105]:
s.value_counts(dropna=False)

1.0    2
2.0    1
NaN    1
Name: count, dtype: int64

In [107]:
df=pd.DataFrame({
    'A':[1,2,2,3],
    'B':['x','y','x','x']
})
print(df['A'].value_counts())

A
2    2
1    1
3    1
Name: count, dtype: int64

In [109]:
print(df['B'].value_counts())

B
x    3
y    1
Name: count, dtype: int64

In [110]:
print(df['B'].value_counts(normalize=True))

B
x    0.75
y    0.25
Name: proportion, dtype: float64

In [198]:
df=pd.read_csv(r"C:\Users\masir\Downloads\Housing.csv")
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [201]:
df['airconditioning'].value_counts()

airconditioning
no     373
yes    172
Name: count, dtype: int64

In [204]:
df.loc[:,['furnishingstatus','mainroad']].value_counts()

furnishingstatus  mainroad
semi-furnished    yes         196
unfurnished       yes         141
furnished         yes         131
unfurnished       no           37
semi-furnished    no           31
furnished         no            9
Name: count, dtype: int64

In [213]:
df[(df['area']>4000) & (df['bedrooms']>4)].loc[:,['mainroad','guestroom']].value_counts()

mainroad  guestroom
yes       no           5
          yes          2
no        no           1
Name: count, dtype: int64

In [214]:
df.loc[:,['mainroad','guestroom']].value_counts()

mainroad  guestroom
yes       no           378
          yes           90
no        no            70
          yes            7
Name: count, dtype: int64

# to_frame() and squeeze()

In [70]:
s = pd.Series([10, 20, 30], name='marks')
df = s.to_frame() 
df

   marks
0     10
1     20
2     30

In [71]:
s = pd.Series([100, 200, 300], index=['math', 'eng', 'sci'])
df = s.to_frame(name='scores')
print(df)

      scores
math     100
eng      200
sci      300

In [72]:
s = pd.Series(['A', 'B', 'C'])
print(s.to_frame())

   0
0  A
1  B
2  C

In [73]:
s = pd.Series([25, 30, 35], index=['A', 'B', 'C'], name='Age')
df = s.to_frame()
print(df)
df['Salary'] = [50000, 60000, 70000]
print(df)

   Age
A   25
B   30
C   35
   Age  Salary
A   25   50000
B   30   60000
C   35   70000

In [75]:
index = pd.MultiIndex.from_tuples(
    [('class1', 'A'), ('class1', 'B'), ('class2', 'A')]
)
s = pd.Series([90, 85, 88], index=index, name='score')
print(s)
df = s.to_frame()
print(df)

class1  A    90
        B    85
class2  A    88
Name: score, dtype: int64
          score
class1 A     90
       B     85
class2 A     88

In [76]:
s = pd.Series({'Alice': 10, 'Bob': 20, 'Charlie': 30}, name='Marks')
df = s.to_frame().reset_index()
print(df)

     index  Marks
0    Alice     10
1      Bob     20
2  Charlie     30

In [84]:
import pandas as pd

df = pd.DataFrame([[10], [20], [30]], columns=['Marks'])
print("Original shape:", df.shape)
print(df.squeeze())
print(df.squeeze().shape)

Original shape: (3, 1)
0    10
1    20
2    30
Name: Marks, dtype: int64
(3,)

In [85]:
df = pd.DataFrame([[85, 90, 95]], columns=['Math', 'Sci', 'Eng'])
print("Original shape:", df.shape)
print(df.squeeze())

Original shape: (1, 3)
Math    85
Sci     90
Eng     95
Name: 0, dtype: int64

In [17]:
df = pd.DataFrame([999, 888], columns=['A'])
print(df)
ds = df.squeeze()
ds.name = 'Integers'
print(ds)

     A
0  999
1  888
0    999
1    888
Name: Integers, dtype: int64

# Slicing and Indexing

In [2]:
import pandas as pd

s = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'], name='Numbers')
print(s)

a    10
b    20
c    30
d    40
e    50
Name: Numbers, dtype: int64

In [49]:
print(s['a'])
print(s['b'])
print(s['c'])
print(s['d'])
print(s['e'])

10
20
30
40
50

In [50]:
print(s[['a','c','e']])

a    10
c    30
e    50
Name: Numbers, dtype: int64

In [51]:
print(s[0])     
print(s[[0, 2, 4]])

10
a    10
c    30
e    50
Name: Numbers, dtype: int64

C:\Users\masir\AppData\Local\Temp\ipykernel_23136\2933047819.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])
C:\Users\masir\AppData\Local\Temp\ipykernel_23136\2933047819.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[[0, 2, 4]])

In [52]:
print(s[0:3])

a    10
b    20
c    30
Name: Numbers, dtype: int64

In [53]:
print(s['a':'c'])

a    10
b    20
c    30
Name: Numbers, dtype: int64

In [54]:
print(s[0::2])

a    10
c    30
e    50
Name: Numbers, dtype: int64

In [55]:
print(s['a'::2])

a    10
c    30
e    50
Name: Numbers, dtype: int64

In [4]:
print(s[s>25])

c    30
d    40
e    50
Name: Numbers, dtype: int64

# loc and iloc

In [132]:
df = pd.DataFrame({
    'Name': ['Ram', 'Sam', 'Aru', 'Kia'],
    'Age': [25, 30, 28, 22],
    'City': ['Hyd', 'Del', 'Mum', 'Blr']
}, index=['A','B','C','D']) 
df

  Name  Age City
A  Ram   25  Hyd
B  Sam   30  Del
C  Aru   28  Mum
D  Kia   22  Blr

In [133]:
df.loc['B']

Name    Sam
Age      30
City    Del
Name: B, dtype: object

In [135]:
df.iloc[1]

Name    Sam
Age      30
City    Del
Name: B, dtype: object

In [136]:
df.loc[['A','C'],['Name']]

  Name
A  Ram
C  Aru

In [137]:
df.iloc[[0,2],[0]]

  Name
A  Ram
C  Aru

In [139]:
df.loc['A':'B']

  Name  Age City
A  Ram   25  Hyd
B  Sam   30  Del

In [141]:
df.iloc[0:2]

  Name  Age City
A  Ram   25  Hyd
B  Sam   30  Del

In [142]:
df.loc['B':'D','Age':'City']

   Age City
B   30  Del
C   28  Mum
D   22  Blr

In [143]:
df.iloc[1:,1:]

   Age City
B   30  Del
C   28  Mum
D   22  Blr

In [145]:
df.loc[['A','C','D'],['Name','City']]

  Name City
A  Ram  Hyd
C  Aru  Mum
D  Kia  Blr

In [147]:
df.loc[df['Age']>25,['Name','City']]

  Name City
B  Sam  Del
C  Aru  Mum

In [148]:
df=pd.read_csv(r"C:\Users\masir\Downloads\Housing.csv")

In [149]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [182]:
df.loc[3,'bedrooms']

4

In [183]:
df.iloc[544,5]

'yes'

In [165]:
print(df.loc[:5,'bedrooms'])

0    4
1    4
2    3
3    4
4    4
5    3
Name: bedrooms, dtype: int64

In [169]:
print(df.loc[500:505,['bedrooms','area','price']])

     bedrooms  area    price
500         3  2800  2660000
501         3  2430  2660000
502         2  3480  2660000
503         3  4000  2660000
504         2  3185  2653000
505         3  4000  2653000

In [170]:
print(df.loc[[1,4,500],['bedrooms','area','price']])

     bedrooms  area     price
1           4  8960  12250000
4           4  7420  11410000
500         3  2800   2660000

In [176]:
df.loc[0:5,'bedrooms':'basement']

   bedrooms  bathrooms  stories mainroad guestroom basement
0         4          2        3      yes        no       no
1         4          4        4      yes        no       no
2         3          2        2      yes        no      yes
3         4          2        2      yes        no      yes
4         4          1        2      yes       yes      yes
5         3          3        1      yes        no      yes

In [171]:
df.iloc[:5,[1]]

   area
0  7420
1  8960
2  9960
3  7500
4  7420

In [173]:
df.iloc[[1,400,400,533],[1]]

     area
1    8960
400  3512
400  3512
533  2400

In [174]:
df.iloc[[1,400,400,533],[0,2,5,6]]

        price  bedrooms mainroad guestroom
1    12250000         4      yes        no
400   3500000         2      yes        no
400   3500000         2      yes        no
533   2100000         3      yes        no

In [177]:
df.iloc[50:55,1:5]

    area  bedrooms  bathrooms  stories
50  7440         3          2        4
51  6325         3          1        4
52  6000         4          2        4
53  5150         3          2        4
54  6000         3          2        2

# Cnditional Selection

In [184]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [185]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [187]:
df[df['mainroad']=='yes']

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,1890000,1700,3,1,2,yes,no,no,no,no,0,no,unfurnished
538,1890000,3649,2,1,1,yes,no,no,no,no,0,no,unfurnished
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [191]:
df[df['mainroad']=='yes'].loc[:5,['area','price','bedrooms']]

   area     price  bedrooms
0  7420  13300000         4
1  8960  12250000         4
2  9960  12250000         3
3  7500  12215000         4
4  7420  11410000         4
5  7500  10850000         3

In [196]:
df[df['area']>4000].loc[:,['area','stories','basement']]

     area  stories basement
0    7420        3       no
1    8960        4       no
2    9960        2      yes
3    7500        2      yes
4    7420        2      yes
..    ...      ...      ...
508  4400        1       no
513  4400        2       no
519  4840        2       no
520  7700        1       no
531  5300        1       no

[338 rows x 3 columns]

In [197]:
df[df['parking']>2].loc[:,'parking']

1      3
3      3
47     3
93     3
225    3
247    3
299    3
304    3
323    3
331    3
401    3
472    3
Name: parking, dtype: int64

In [207]:
df[(df['area']>4000) & (df['mainroad']=='yes')].iloc[:,[1,5]]

     area mainroad
0    7420      yes
1    8960      yes
2    9960      yes
3    7500      yes
4    7420      yes
..    ...      ...
494  6800      yes
508  4400      yes
513  4400      yes
519  4840      yes
520  7700      yes

[316 rows x 2 columns]

In [208]:
df[(df['furnishingstatus']=='furnished') & (df['parking']>2)]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
47,7490000,6600,3,1,4,yes,no,no,no,yes,3,yes,furnished
299,4200000,7000,3,1,1,yes,no,no,no,no,3,no,furnished
331,3920000,7260,3,2,1,yes,yes,yes,no,no,3,no,furnished

In [210]:
df[(df['furnishingstatus']=='furnished') | (df['parking']>2)].loc[:,['price' ,'area' ,'parking' ,'furnishingstatus']]

        price  area  parking furnishingstatus
0    13300000  7420        2        furnished
1    12250000  8960        3        furnished
3    12215000  7500        3        furnished
4    11410000  7420        2        furnished
8     9870000  8100        2        furnished
..        ...   ...      ...              ...
509   2590000  3600        1        furnished
512   2520000  3000        0        furnished
522   2380000  2475        0        furnished
523   2380000  2787        0        furnished
543   1750000  2910        0        furnished

[147 rows x 4 columns]

# values

In [10]:
s=pd.Series([1,2,3,4],name='nums')
print(s)
print(s.values)
print(type(s.values))
print((s.values).dtype)

0    1
1    2
2    3
3    4
Name: nums, dtype: int64
[1 2 3 4]
<class 'numpy.ndarray'>
int64

In [11]:
s1=pd.Series(['apple','banana','grapes'])
print(s1.values)

['apple' 'banana' 'grapes']

In [12]:
s = pd.Series([1, 2.5, 'text', True])
print(s.values)
print((s.values).dtype)

[1 2.5 'text' True]
object

In [14]:
s = pd.Series([2, 4, 6, 8])
print(np.mean(s.values))  
print(np.max(s.values))

5.0
8

# Basic Statistics

In [266]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [267]:
df['price'].mean()

4766729.247706422

In [268]:
# avg price of an flat with  1 bed rooms and fully furnished
sample=df[(df['bedrooms']==1)&(df['furnishingstatus']=='furnished')]
avg_price=sample['price'].mean() 
avg_price

3150000.0

In [269]:
# avg price of an flat with  1 bed rooms and fully furnished
sample=df[(df['bedrooms']==1)&(df['furnishingstatus']=='unfurnished')]
avg_price=sample['price'].mean()
avg_price

2275000.0

In [270]:
# avg price of an flat with  1 bed rooms and seminfurnished
sample=df[(df['bedrooms']==1)&(df['furnishingstatus']=='semi-furnished')]
avg_price=sample['price'].mean()
avg_price

nan

In [271]:
# avg price of an flat with  2 bed rooms and fully furnished
sample=df[(df['bedrooms']==2)&(df['furnishingstatus']=='furnished')]
avg_price=sample['price'].mean()
avg_price

4128068.9655172415

In [272]:
# avg price of an flat with  2 bed rooms and unfurnished
sample=df[(df['bedrooms']==2)&(df['furnishingstatus']=='unfurnished')]
avg_price=sample['price'].mean()
avg_price

3070666.6666666665

In [273]:
# avg price of an flat with  2 bed rooms and seminfurnished
sample=df[(df['bedrooms']==2)&(df['furnishingstatus']=='semi-furnished')]
avg_price=sample['price'].mean()
avg_price

3984260.0

In [274]:
df['price'].min()

1750000

In [275]:
df['price'].max(),df['price'].var(),df['price'].std()

(13300000, 3498544355820.573, 1870439.6156573922)

In [276]:
df['price'].skew(),df['price'].kurt()

(1.2122388370279802, 1.9601302314151994)

In [277]:
df.loc[:5,'price'].cumsum(),df.loc[:5,'price'].cumprod()

(0    13300000
 1    25550000
 2    37800000
 3    50015000
 4    61425000
 5    72275000
 Name: price, dtype: int64,
 0               13300000
 1        162925000000000
 2    3582890039368425472
 3   -9164455036325789696
 4    6728501608057929728
 5   -1602874025221029888
 Name: price, dtype: int64)

In [278]:
df.loc[:5,'price'].cummax(),df.loc[:5,'price'].cummin()

(0    13300000
 1    13300000
 2    13300000
 3    13300000
 4    13300000
 5    13300000
 Name: price, dtype: int64,
 0    13300000
 1    12250000
 2    12250000
 3    12215000
 4    11410000
 5    10850000
 Name: price, dtype: int64)

In [279]:
df['price'].quantile(0.25)

3430000.0

In [280]:
df['price'].corr(df['area'])

0.5359973457780801

In [281]:
df['price'].cov(df['area'])

2175676334.874865

In [282]:
df['price'].idxmax()

0

In [283]:
df['price'].idxmin()

542

# describe()

In [284]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [297]:
df.describe(include='all')

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545,545,545,545,545,545.000000,545,545
unique,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2,NaN,2,3
top,NaN,NaN,NaN,NaN,NaN,yes,no,no,no,no,NaN,no,semi-furnished
freq,NaN,NaN,NaN,NaN,NaN,468,448,354,520,373,NaN,417,227
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,NaN,NaN,NaN,NaN,NaN,0.693578,NaN,NaN
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,NaN,NaN,NaN,NaN,NaN,0.861586,NaN,NaN
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,NaN

In [291]:
df.describe(percentiles=[0.25,0.75,0.89])

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
89%,7.151200e+06,7711.200000,4.000000,2.000000,3.000000,2.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [293]:
df.describe(percentiles=[0.25,0.75,0.89],exclude='number')

,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
count,545,545,545,545,545,545,545
unique,2,2,2,2,2,2,3
top,yes,no,no,no,no,no,semi-furnished
freq,468,448,354,520,373,417,227

In [294]:
df.describe(percentiles=[0.25,0.75,0.89],exclude='object')

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
89%,7.151200e+06,7711.200000,4.000000,2.000000,3.000000,2.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [295]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

# counts

In [298]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [299]:
df.count()

price               545
area                545
bedrooms            545
bathrooms           545
stories             545
mainroad            545
guestroom           545
basement            545
hotwaterheating     545
airconditioning     545
parking             545
prefarea            545
furnishingstatus    545
dtype: int64

In [300]:
df.count(numeric_only=True)

price        545
area         545
bedrooms     545
bathrooms    545
stories      545
parking      545
dtype: int64

In [304]:
df.count(axis=1),df.count(axis=0)

(0      13
 1      13
 2      13
 3      13
 4      13
        ..
 540    13
 541    13
 542    13
 543    13
 544    13
 Length: 545, dtype: int64,
 price               545
 area                545
 bedrooms            545
 bathrooms           545
 stories             545
 mainroad            545
 guestroom           545
 basement            545
 hotwaterheating     545
 airconditioning     545
 parking             545
 prefarea            545
 furnishingstatus    545
 dtype: int64)

In [312]:
s = pd.Series([10, None, 30, 40])
s.count()

3

In [315]:
df = pd.DataFrame({
    'A': [1, None, 3],
    'B': [None, 2, 3],
    'C': [4, 5, None]
})

df.count(axis=1)

0    2
1    2
2    2
dtype: int64

In [316]:
df.count(axis=0)

A    2
B    2
C    2
dtype: int64

In [318]:
df = pd.DataFrame({
    'A': [1, 2, None],
    'B': ['a', 'b', None],
    'C': [10.5, None, 20.1]
})

df.count(numeric_only=True)

A    2
C    2
dtype: int64

# concat()

In [4]:
s1=pd.Series(np.random.randint(10,50,10),name='marks')
s2=pd.Series(np.random.choice(['Male','Female','other'],10),name='genders')
print(s1,s2)

0    36
1    39
2    10
3    28
4    23
5    42
6    10
7    46
8    19
9    17
Name: marks, dtype: int32 0      Male
1    Female
2      Male
3      Male
4    Female
5     other
6    Female
7     other
8      Male
9    Female
Name: genders, dtype: object

In [5]:
pd.concat([s1,s2])

0        36
1        39
2        10
3        28
4        23
5        42
6        10
7        46
8        19
9        17
0      Male
1    Female
2      Male
3      Male
4    Female
5     other
6    Female
7     other
8      Male
9    Female
dtype: object

In [6]:
pd.concat([s1,s2],axis=1)

   marks genders
0     36    Male
1     39  Female
2     10    Male
3     28    Male
4     23  Female
5     42   other
6     10  Female
7     46   other
8     19    Male
9     17  Female

In [8]:
df1 = pd.DataFrame({'A':[1,2], 'B':[3,4]})
df2 = pd.DataFrame({'A':[5,6], 'B':[7,8]})
result = pd.concat([df1, df2])
print(result)

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [10]:
pd.concat([df1, df2], ignore_index=True)

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [11]:
pd.concat([df1, df2], axis=1)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [13]:
df1 = pd.DataFrame({'A':[1,2], 'B':[3,4]})
df2 = pd.DataFrame({'A':[5,6], 'C':[7,8]})

pd.concat([df1, df2],ignore_index=True)

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
2  5  NaN  7.0
3  6  NaN  8.0

In [14]:
pd.concat([df1, df2], join='inner')

   A
0  1
1  2
0  5
1  6

In [16]:
df1 = pd.DataFrame({'A':[1,2], 'B':[3,4]})
df2 = pd.DataFrame({'A':[5,6], 'C':[7,8],'B':[9,10]})
pd.concat([df1, df2], join='inner')

   A   B
0  1   3
1  2   4
0  5   9
1  6  10

In [19]:
df1 = pd.DataFrame({'A':[1,2], 'B':[3,4]})
df2 = pd.DataFrame({'A':[5,6], 'B':[7,8]})
pd.concat([df1, df2], keys=['first', 'second'])

          A  B
first  0  1  3
       1  2  4
second 0  5  7
       1  6  8

In [22]:
df1 = pd.DataFrame({'x':[10,20]}, index=['a','b'])
df2 = pd.DataFrame({'y':[30,40]}, index=['c','d'])

pd.concat([df1, df2])

      x     y
a  10.0   NaN
b  20.0   NaN
c   NaN  30.0
d   NaN  40.0

In [23]:
df1 = pd.DataFrame({'A':[1,2,3]})
df2 = pd.DataFrame({'B':[4,5]})

pd.concat([df1, df2], axis=1)

   A    B
0  1  4.0
1  2  5.0
2  3  NaN

In [25]:
df1=pd.read_csv(r"C:\Users\masir\Downloads\coffee_shop_sales2.csv")
df1

         Day  Cups Sold  Avg Temp (°C) FootBall Match (Yes/No)
0     Monday        154             24                      No
1    Tuesday        143             23                      No
2  Wednesday        166             26                      No
3   Thursday        142             22                      No
4     Friday        203             33                     Yes
5   Saturday        214             34                     Yes
6     Sunday        202             32                     Yes

In [29]:
revenue=pd.Series(np.random.choice(['Yes','No'],7),name='Discounts Offered')

In [35]:
pd.concat([df1,revenue],axis=1)

,Day,Cups Sold,Avg Temp (°C),FootBall Match (Yes/No),Discounts Offered
0,Monday,154,24,No,No
1,Tuesday,143,23,No,Yes
2,Wednesday,166,26,No,No
3,Thursday,142,22,No,Yes
4,Friday,203,33,Yes,Yes
5,Saturday,214,34,Yes,Yes
6,Sunday,202,32,Yes,Yes

# tail() & head()

In [36]:
df=pd.read_csv(r"C:\Users\masir\Downloads\loan_data_set.csv")

In [38]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [39]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [43]:
df.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N

In [41]:
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [44]:
df.tail(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
604,LP002959,Female,Yes,1,Graduate,No,12000,0.0,496.0,360.0,1.0,Semiurban,Y
605,LP002960,Male,Yes,0,Not Graduate,No,2400,3800.0,NaN,180.0,1.0,Urban,N
606,LP002961,Male,Yes,1,Graduate,No,3400,2500.0,173.0,360.0,1.0,Semiurban,Y
607,LP002964,Male,Yes,2,Not Graduate,No,3987,1411.0,157.0,360.0,1.0,Rural,Y
608,LP002974,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

# isna() & isnull() ----->both are same isnull is aiias of isna

In [49]:
s=pd.Series([10,None,25])
print(s.isna())
print(s.isnull())

[0    False
1     True
2    False
dtype: bool]
0    False
1     True
2    False
dtype: bool

In [50]:
s = pd.Series([10, "hello", None, float('nan')])
s.isna()

0    False
1    False
2     True
3     True
dtype: bool

In [57]:
df = pd.DataFrame({
    'A':[1, None, 3],
    'B':[None, None, 5]
})
print(df.isnull())
df.isna()

       A      B
0  False   True
1   True   True
2  False  False

       A      B
0  False   True
1   True   True
2  False  False

In [59]:
df.isna().sum()

A    1
B    2
dtype: int64

# notna() & notnull()

In [61]:

s = pd.Series([10, None, 25])
s.notna()

0     True
1    False
2     True
dtype: bool

In [62]:
df = pd.DataFrame({
    'A':[1, None, 3],
    'B':[4, 5, None]
})

df.notnull()

       A      B
0   True   True
1  False   True
2   True  False

In [63]:
s[s.notna()]

0    10.0
2    25.0
dtype: float64

In [64]:
df.notna().sum()

A    2
B    2
dtype: int64

# drop()

In [2]:
s=pd.Series([1,2,3],index=['a','b','c'],name='integers')
print(s)

a    1
b    2
c    3
Name: integers, dtype: int64

In [3]:
s.drop(s['a':'c'].index)

Series([], Name: integers, dtype: int64)

In [13]:
print(s.drop('a'))
s

b    2
c    3
Name: integers, dtype: int64

a    1
b    2
c    3
Name: integers, dtype: int64

In [14]:
s.drop(['a','c'],inplace=True)

In [15]:
s.drop(['a','c','d'],inplace=True,errors='ignore')

In [16]:
s

b    2
Name: integers, dtype: int64

In [19]:
df=pd.read_csv(r"C:\Users\masir\Downloads\Housing.csv")
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [21]:
df.drop('price',axis=1)

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...
540,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [22]:
df.drop(['price','area'],axis=1)

,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,4,4,4,yes,no,no,no,yes,3,no,furnished
2,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...
540,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,3,1,1,no,no,no,no,no,0,no,furnished
544,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [23]:
df.drop(0)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [24]:
df.drop([0,1,2])

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [25]:
df.drop(columns=['price','area','gender'],inplace=True,errors='ignore')

In [26]:
df

,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,4,4,4,yes,no,no,no,yes,3,no,furnished
2,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...
540,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,3,1,1,no,no,no,no,no,0,no,furnished
544,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [27]:
df.drop(index=[0,1,4,6],inplace=True)

In [28]:
df

,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
2,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,4,2,2,yes,no,yes,no,yes,3,yes,furnished
5,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
7,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
...,...,...,...,...,...,...,...,...,...,...,...
540,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,3,1,1,no,no,no,no,no,0,no,furnished
544,3,1,2,yes,no,no,no,no,0,no,unfurnished

# sort_values()

In [2]:
df=pd.DataFrame(
    {'price':[300,None,100,200]}
)
df

   price
0  300.0
1    NaN
2  100.0
3  200.0

In [6]:
df.sort_values('price',na_position='first')

   price
1    NaN
2  100.0
3  200.0
0  300.0

In [7]:
df=pd.DataFrame({
    'price':[100,200,100,200],
    'rating':[4,5,3,2]
})
df.sort_values(['price','rating'],ascending=[True,False])

   price  rating
0    100       4
2    100       3
1    200       5
3    200       2

In [9]:
df=pd.DataFrame({'col':[[3,4],[1,2],[1,2,3]]})
df['col']=df['col'].astype(str)
df.sort_values('col')

         col
2  [1, 2, 3]
1     [1, 2]
0     [3, 4]

In [12]:
df=pd.DataFrame({'price':[50,200,150,300]})
df[df['price']>100].sort_values('price')

   price
2    150
1    200
3    300

# sort_index()

In [14]:
df=pd.DataFrame({'A':[10,20,30]})
df.index=['c','a','b']
df.sort_index()

    A
a  20
b  30
c  10

In [17]:
df=pd.DataFrame({'c':[1,2],'a':[3,4],'b':[5,6]})
print(df)
df.sort_index(axis=1)

   c  a  b
0  1  3  5
1  2  4  6

   a  b  c
0  3  5  1
1  4  6  2

In [21]:
df=pd.DataFrame({'val':[10,20,30,40]},index=pd.MultiIndex.from_tuples([
    ('B',2),
    ('B',1),
    ('A',2),
    ('A',1)
]))
df.sort_index(level=[0,1])

     val
A 1   40
  2   30
B 1   20
  2   10

In [22]:
df=pd.DataFrame({'A':[10,20,30]})
df.index=[100,50,200]
df.sort_index(ascending=False)

      A
200  30
100  10
50   20

In [28]:
df=pd.DataFrame({
    'id':[3,1,2],
    'name':['A','B','C']
})
df.set_index('id',inplace=True)
df.sort_index()

   name
id
1     B
2     C
3     A

# Data Cleaning

# dropna()

In [29]:
df=pd.DataFrame({'A':[1,None,5],
                'B':[2,None,None]})
df

     A    B
0  1.0  2.0
1  NaN  NaN
2  5.0  NaN

In [30]:
df.dropna()

     A    B
0  1.0  2.0

In [31]:
df.dropna(how='all')

     A    B
0  1.0  2.0
2  5.0  NaN

In [33]:
df=pd.DataFrame({'A':[1,4],
                'B':[None,5],
                'C':[3,None]})
df

   A    B    C
0  1  NaN  3.0
1  4  5.0  NaN

In [35]:
df.dropna(axis=1,how='any')

   A
0  1
1  4

In [36]:
df.dropna(axis=1,how='all')

   A    B    C
0  1  NaN  3.0
1  4  5.0  NaN

In [40]:
df=pd.DataFrame({
    'A':[1,2,None],
    'B':[None,3,4],
    'C':[None,None,5],
    'D':[None,None,None]
})
df

     A    B    C     D
0  1.0  NaN  NaN  None
1  2.0  3.0  NaN  None
2  NaN  4.0  5.0  None

In [43]:
df.dropna(thresh=2)

     A    B    C     D
1  2.0  3.0  NaN  None
2  NaN  4.0  5.0  None

In [45]:
df.dropna(thresh=2,axis=1)

     A    B
0  1.0  NaN
1  2.0  3.0
2  NaN  4.0

In [46]:
df=pd.DataFrame({'A':[1,3,6],
                  'B':[2,None,7],
                'C':[None,5,8]})
df

   A    B    C
0  1  2.0  NaN
1  3  NaN  5.0
2  6  7.0  8.0

In [47]:
df.dropna(subset=['B','C'])

   A    B    C
2  6  7.0  8.0

# fillna()

In [54]:
df=pd.DataFrame({
    'A':[1,None,5],
    'B':[None,4,None],
    'c':[None,6,None]
})
df

     A    B    c
0  1.0  NaN  NaN
1  NaN  4.0  6.0
2  5.0  NaN  NaN

In [55]:
df.fillna(0)

     A    B    c
0  1.0  0.0  0.0
1  0.0  4.0  6.0
2  5.0  0.0  0.0

In [56]:
df.fillna(0,axis=1,limit=1)

     A    B    c
0  1.0  0.0  NaN
1  0.0  4.0  6.0
2  5.0  0.0  NaN

In [63]:
df=pd.DataFrame({
    'A':[1,None,5],
    'B':[None,4,None],
    'c':[None,6,None]
})
df.fillna(4,limit=1)

     A    B    c
0  1.0  4.0  4.0
1  4.0  4.0  6.0
2  5.0  NaN  NaN

In [64]:
df.loc[0] = df.loc[0].fillna(4)
# fill only 1st row

In [65]:
df

     A    B    c
0  1.0  4.0  4.0
1  NaN  4.0  6.0
2  5.0  NaN  NaN

In [66]:
df=pd.DataFrame({
    'A':[1,None,5],
    'B':[None,4,None],
    'c':[None,6,None]
})
df

     A    B    c
0  1.0  NaN  NaN
1  NaN  4.0  6.0
2  5.0  NaN  NaN

In [67]:
df['A']=df['A'].fillna(df['A'].mean())

In [68]:
df

     A    B    c
0  1.0  NaN  NaN
1  3.0  4.0  6.0
2  5.0  NaN  NaN

In [70]:
df['B']=df['B'].fillna(df['B'].median())

In [71]:
df

     A    B    c
0  1.0  4.0  NaN
1  3.0  4.0  6.0
2  5.0  4.0  NaN

In [74]:
df=pd.DataFrame({
    'A':[1,None,5],
    'B':[None,4,None],
    'c':[None,6,None]
})
df.fillna(method='ffill')

C:\Users\masir\AppData\Local\Temp\ipykernel_21736\81921219.py:6: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     A    B    c
0  1.0  NaN  NaN
1  1.0  4.0  6.0
2  5.0  4.0  6.0

In [75]:
df=pd.DataFrame({
    'A':[1,None,5],
    'B':[None,4,None],
    'c':[None,6,None]
})
df.fillna(method='bfill')

C:\Users\masir\AppData\Local\Temp\ipykernel_21736\711003495.py:6: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

     A    B    c
0  1.0  4.0  6.0
1  5.0  4.0  6.0
2  5.0  NaN  NaN

In [76]:
df=pd.DataFrame({
    'A':[1,None,5],
    'B':[None,4,None],
    'c':[None,6,None]
})
df.bfill()

     A    B    c
0  1.0  4.0  6.0
1  5.0  4.0  6.0
2  5.0  NaN  NaN

In [79]:
df=pd.DataFrame({
    'A':[1,None,5],
    'B':[None,4,None],
    'C':[None,6,None]
})
df.fillna({'A':df['A'].mean(),
           'B':df['B'].mean(),
           'C':df['C'].mean()})

     A    B    C
0  1.0  4.0  6.0
1  3.0  4.0  6.0
2  5.0  4.0  6.0

In [81]:
df=pd.DataFrame({
    'A':[1,None,5],
    'B':[None,4,None],
    'C':[None,6,None]
})
df['C'].mean()

6.0

# replace()

In [83]:
df=pd.DataFrame({'A':[5,10,20,30,40,10],'B':[30,50,90,80,10,10]})
df.replace(10,99)

    A   B
0   5  30
1  99  50
2  20  90
3  30  80
4  40  99
5  99  99

In [84]:
df.replace([10,30],[49,99])

    A   B
0   5  99
1  49  50
2  20  90
3  99  80
4  40  49
5  49  49

In [87]:
df.replace({'A':{10:49,30:99,5:999}})

     A   B
0  999  30
1   49  50
2   20  90
3   99  80
4   40  10
5   49  10

# clip()

In [97]:
df=pd.DataFrame({
    'A':[5,15,25,35,45,55],
    'B':[10,20,30,40,50,60]
})
df

    A   B
0   5  10
1  15  20
2  25  30
3  35  40
4  45  50
5  55  60

In [98]:
df.clip(upper=50)

    A   B
0   5  10
1  15  20
2  25  30
3  35  40
4  45  50
5  50  50

In [99]:
df.clip(lower=20)

    A   B
0  20  20
1  20  20
2  25  30
3  35  40
4  45  50
5  55  60

In [100]:
df

    A   B
0   5  10
1  15  20
2  25  30
3  35  40
4  45  50
5  55  60

In [101]:
df.clip(lower=20,upper=50)

    A   B
0  20  20
1  20  20
2  25  30
3  35  40
4  45  50
5  50  50

In [103]:
df['A'].clip(lower=30,upper=50)

0    30
1    30
2    30
3    35
4    45
5    50
Name: A, dtype: int64

# select_dtypes()

In [104]:
df=pd.read_csv(r"C:\Users\masir\Downloads\Housing.csv")

In [105]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [107]:
df.select_dtypes(include='int64',exclude='object')

        price  area  bedrooms  bathrooms  stories  parking
0    13300000  7420         4          2        3        2
1    12250000  8960         4          4        4        3
2    12250000  9960         3          2        2        2
3    12215000  7500         4          2        2        3
4    11410000  7420         4          1        2        2
..        ...   ...       ...        ...      ...      ...
540   1820000  3000         2          1        1        2
541   1767150  2400         3          1        1        0
542   1750000  3620         2          1        1        0
543   1750000  2910         3          1        1        0
544   1750000  3850         3          1        2        0

[545 rows x 6 columns]

In [108]:
df.select_dtypes(include='object',exclude='int64')

,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
0,yes,no,no,no,yes,yes,furnished
1,yes,no,no,no,yes,no,furnished
2,yes,no,yes,no,no,yes,semi-furnished
3,yes,no,yes,no,yes,yes,furnished
4,yes,yes,yes,no,yes,no,furnished
...,...,...,...,...,...,...,...
540,yes,no,yes,no,no,no,unfurnished
541,no,no,no,no,no,no,semi-furnished
542,yes,no,no,no,no,no,unfurnished
543,no,no,no,no,no,no,furnished
544,yes,no,no,no,no,no,unfurnished

In [111]:
df.select_dtypes(include=['int64','object'],exclude='float64')

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

# duplicated()

In [114]:
df=pd.DataFrame({
    'A':[1,2,2,3,2],
    'B':['x','y','y','z','y']
})
df

   A  B
0  1  x
1  2  y
2  2  y
3  3  z
4  2  y

In [115]:
df.duplicated()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [116]:
df.duplicated(subset=['A'])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [117]:
df.duplicated(subset=['B'])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [118]:
df.duplicated(keep='last')

0    False
1     True
2     True
3    False
4    False
dtype: bool

# drop_duplicates()

In [119]:
df = pd.DataFrame({
    'A':[1, 2, 2, 3, 2],
    'B':['x','y','y','z','y']
})

In [121]:
df.drop_duplicates()

   A  B
0  1  x
1  2  y
3  3  z

In [120]:
df.drop_duplicates(subset=['A'])

   A  B
0  1  x
1  2  y
3  3  z

In [122]:
df.drop_duplicates(subset=['B'])

   A  B
0  1  x
1  2  y
3  3  z

In [123]:
df.drop_duplicates(keep='last')

   A  B
0  1  x
3  3  z
4  2  y

In [124]:
df.drop_duplicates(keep=False)

   A  B
0  1  x
3  3  z

# merge()

In [3]:
df1=pd.DataFrame({
    'City':['New york','Chicago','Orlando'],
    'Temperature':[21,14,35]
})
df1

       City  Temperature
0  New york           21
1   Chicago           14
2   Orlando           35

In [8]:
df2=pd.DataFrame({'City':['Chicago','New york','Orlando']
                 ,'Humidity':[65,68,75]})
df2

       City  Humidity
0   Chicago        65
1  New york        68
2   Orlando        75

In [9]:
pd.merge(df1,df2,on='City')

       City  Temperature  Humidity
0  New york           21        68
1   Chicago           14        65
2   Orlando           35        75

In [10]:
df1=pd.DataFrame({
    'City':['New york','Chicago','Orlando','baltmore'],
    'Temperature':[21,14,35,32]
})
df2=pd.DataFrame({'City':['Chicago','New york','Orlando','sam francis']
                 ,'Humidity':[65,68,75,71]})

In [11]:
pd.merge(df1,df2,on='City')

       City  Temperature  Humidity
0  New york           21        68
1   Chicago           14        65
2   Orlando           35        75

In [15]:
pd.merge(df1,df2,on='City',how='outer')

          City  Temperature  Humidity
0      Chicago         14.0      65.0
1     New york         21.0      68.0
2      Orlando         35.0      75.0
3     baltmore         32.0       NaN
4  sam francis          NaN      71.0

In [16]:
pd.merge(df1,df2,on='City',how='left')

       City  Temperature  Humidity
0  New york           21      68.0
1   Chicago           14      65.0
2   Orlando           35      75.0
3  baltmore           32       NaN

In [18]:
pd.merge(df1,df2,on='City',how='right',indicator=True)

          City  Temperature  Humidity      _merge
0      Chicago         14.0        65        both
1     New york         21.0        68        both
2      Orlando         35.0        75        both
3  sam francis          NaN        71  right_only

In [19]:
df1=pd.DataFrame({'id':[1,2,3],'name':['A','B','C']})
df2=pd.DataFrame({'emp_id':[2,3,4],'score':[90,80,70]})

In [20]:
pd.merge(df1,df2,left_on='id',right_on='emp_id',how='inner')

   id name  emp_id  score
0   2    B       2     90
1   3    C       3     80

In [28]:
df3=pd.DataFrame({'id':[1,2,2],'year':[2023,2023,2024]})
df4=pd.DataFrame({'id':[2,2,1],'year':[2023,2024,2023],'bonus':[5,6,7]})

In [29]:
pd.merge(df3,df4,on=['id','year'],how='inner')

   id  year  bonus
0   1  2023      7
1   2  2023      5
2   2  2024      6

In [31]:
pd.merge(df1,df2,left_on='id',right_on='emp_id',how='outer',indicator=True)

    id name  emp_id  score      _merge
0  1.0    A     NaN    NaN   left_only
1  2.0    B     2.0   90.0        both
2  3.0    C     3.0   80.0        both
3  NaN  NaN     4.0   70.0  right_only

In [34]:
df1_i=df1.set_index('id')
df1_i

   name
id
1     A
2     B
3     C

In [37]:
df2_i=df2.set_index('emp_id')
df2_i

        score
emp_id
2          90
3          80
4          70

In [38]:
pd.merge(df1_i,df2_i,left_index=True,right_index=True,how='inner')

  name  score
2    B     90
3    C     80

In [42]:
m=pd.merge(df1,df2,left_on='id',right_on='emp_id',how='outer')
m

    id name  emp_id  score
0  1.0    A     NaN    NaN
1  2.0    B     2.0   90.0
2  3.0    C     3.0   80.0
3  NaN  NaN     4.0   70.0

In [43]:
m.fillna('Missing')

        id     name   emp_id    score
0      1.0        A  Missing  Missing
1      2.0        B      2.0     90.0
2      3.0        C      3.0     80.0
3  Missing  Missing      4.0     70.0

In [53]:
df3=pd.DataFrame({'id':[1,2,2],'year':[2023,2023,2024]})
df4=pd.DataFrame({'id':[2,2,1],'year':[2023,2024,2023],'bonus':[5,6,7]})

In [58]:
pd.merge(df3,df4,on='id',how='inner')

   id  year_x  year_y  bonus
0   1    2023    2023      7
1   2    2023    2023      5
2   2    2023    2024      6
3   2    2024    2023      5
4   2    2024    2024      6

# join()

In [62]:
df1=pd.DataFrame({
    'City':['New york','Chicago','Orlando'],
    'Temperature':[21,14,35]
})
df1

       City  Temperature
0  New york           21
1   Chicago           14
2   Orlando           35

In [63]:
df2=pd.DataFrame({'City':['Chicago','New york','Orlando']
                 ,'Humidity':[65,68,75]})
df2

       City  Humidity
0   Chicago        65
1  New york        68
2   Orlando        75

In [66]:
df1.join(df2.set_index('City'),on='City')

       City  Temperature  Humidity
0  New york           21        68
1   Chicago           14        65
2   Orlando           35        75

In [68]:
df1=pd.DataFrame({
    'City':['New york','Chicago','Orlando','baltmore'],
    'Temperature':[21,14,35,32]
})
df2=pd.DataFrame({'City':['Chicago','New york','Orlando','sam francis']
                 ,'Humidity':[65,68,75,71]})
df1.join(df2.set_index('City'),on='City',how='outer')

            City  Temperature  Humidity
1.0      Chicago         14.0      65.0
0.0     New york         21.0      68.0
2.0      Orlando         35.0      75.0
3.0     baltmore         32.0       NaN
NaN  sam francis          NaN      71.0

In [70]:
df1.join(df2.set_index('City'),on='City',how='left')

       City  Temperature  Humidity
0  New york           21      68.0
1   Chicago           14      65.0
2   Orlando           35      75.0
3  baltmore           32       NaN

In [ ]:
df3=pd.DataFrame({'id':[1,2,2],'year':[2023,2023,2024]})
df4=pd.DataFrame({'id':[2,2,1],'year':[2023,2024,2023],'bonus':[5,6,7]})

In [85]:
df3.join(
    df4.set_index('id'),
    on='id',
    how='inner',
    lsuffix='_df3',
    rsuffix='_df4'
)

   id  year_df3  year_df4  bonus
0   1      2023      2023      7
1   2      2023      2023      5
1   2      2023      2024      6
2   2      2024      2023      5
2   2      2024      2024      6

✅ 1. Purpose
merge()

✅ Designed for SQL-style joins
✅ Works on columns
✅ Most powerful + flexible

join()

✅ Shortcut for merging by index
✅ Simpler but less flexible

✅ 2. How they match rows
Function	Joins on	Example
merge()	Column(s)	merge(df1, df2, on="id")
join()	Index by default	df1.join(df2)
join() (with on=)	Column on left + index on right	df1.join(df2, on="id")

# groupby()

In [3]:
data = {
    'day': [
        '1/1/2017','1/2/2017','1/3/2017','1/4/2017',
        '1/1/2017','1/2/2017','1/3/2017','1/4/2017',
        '1/1/2017','1/2/2017','1/3/2017','1/4/2017'
    ],
    'city': [
        'new york','new york','new york','new york',
        'mumbai','mumbai','mumbai','mumbai',
        'paris','paris','paris','paris'
    ],
    'temperature': [
        32,36,28,33,
        90,85,87,92,
        45,50,54,42
    ],
    'windspeed': [
        6,7,12,7,
        5,12,15,5,
        20,13,8,10
    ],
    'event': [
        'Rain','Sunny','Snow','Sunny',
        'Sunny','Fog','Fog','Rain',
        'Sunny','Cloudy','Cloudy','Cloudy'
    ]
}

df = pd.DataFrame(data)
df

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [5]:
g=df.groupby('city')
g

In [92]:
for city,city_df in g:
    print(city)
    print(city_df)

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [93]:
g.get_group('mumbai')

        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

In [94]:
g.max()

               day  temperature  windspeed  event
city
mumbai    1/4/2017           92         15  Sunny
new york  1/4/2017           36         12  Sunny
paris     1/4/2017           54         20  Sunny

In [97]:
g.mean(numeric_only=True)

          temperature  windspeed
city
mumbai          88.50       9.25
new york        32.25       8.00
paris           47.75      12.75

In [98]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

In [99]:
df=pd.DataFrame({'City':['A','A','B','B','C','C'],
                'Product':['P1','P2','P1','P2','P1','P2'],
                'Sales':[10,20,5,15,50,40],
                'Quantity':[1,2,1,3,5,4]})
df

  City Product  Sales  Quantity
0    A      P1     10         1
1    A      P2     20         2
2    B      P1      5         1
3    B      P2     15         3
4    C      P1     50         5
5    C      P2     40         4

In [103]:
df.groupby(['Product'])['Sales'].sum()

Product
P1    65
P2    75
Name: Sales, dtype: int64

In [110]:
df.groupby('City')[['Sales','Quantity']].agg(['min','max','mean'])

     Sales           Quantity
       min max  mean      min max mean
City
A       10  20  15.0        1   2  1.5
B        5  15  10.0        1   3  2.0
C       40  50  45.0        4   5  4.5

In [111]:
df['city_avg_sales']=df.groupby('City')['Sales'].transform('mean')

In [112]:
df

  City Product  Sales  Quantity  city_avg_sales
0    A      P1     10         1            15.0
1    A      P2     20         2            15.0
2    B      P1      5         1            10.0
3    B      P2     15         3            10.0
4    C      P1     50         5            45.0
5    C      P2     40         4            45.0

In [114]:
df.groupby('City').filter(lambda x:x['Sales'].sum()>50)

  City Product  Sales  Quantity  city_avg_sales
4    C      P1     50         5            45.0
5    C      P2     40         4            45.0

# crosstab()

In [2]:
df = pd.DataFrame({
    'Gender': ['M','F','M','F','F','M','M','F'],
    'Department': ['HR','IT','IT','HR','HR','IT','Sales','Sales'],
    'Experience': [2,5,3,2,7,4,1,3],
    'Salary': [50,70,60,40,80,90,30,55]
})

print(df)

  Gender Department  Experience  Salary
0      M         HR           2      50
1      F         IT           5      70
2      M         IT           3      60
3      F         HR           2      40
4      F         HR           7      80
5      M         IT           4      90
6      M      Sales           1      30
7      F      Sales           3      55

In [5]:
pd.crosstab(df['Gender'],df['Department'])

Department  HR  IT  Sales
Gender
F            2   1      1
M            1   2      1

In [6]:
pd.crosstab(df['Gender'],df['Department'],margins=True,margins_name='Total')

Department  HR  IT  Sales  Total
Gender
F            2   1      1      4
M            1   2      1      4
Total        3   3      2      8

In [8]:
pd.crosstab(df['Gender'],df['Department'],values=df['Salary'],aggfunc='sum',margins=True)

Department   HR   IT  Sales  All
Gender
F           120   70     55  245
M            50  150     30  230
All         170  220     85  475

In [10]:
pd.crosstab(df['Gender'],df['Department'],normalize='index')

Department    HR    IT  Sales
Gender
F           0.50  0.25   0.25
M           0.25  0.50   0.25

In [11]:
pd.crosstab(
    [df['Gender'], df['Department']],
    df['Experience']
)

Experience         1  2  3  4  5  7
Gender Department
F      HR          0  1  0  0  0  1
       IT          0  0  0  0  1  0
       Sales       0  0  1  0  0  0
M      HR          0  1  0  0  0  0
       IT          0  0  1  1  0  0
       Sales       1  0  0  0  0  0

In [12]:
pd.crosstab(
    [df['Gender'], df['Department']],
    df['Experience'] > 3
)

Experience         False  True
Gender Department
F      HR              1      1
       IT              0      1
       Sales           1      0
M      HR              1      0
       IT              1      1
       Sales           1      0

In [13]:
pd.crosstab(
    [df['Gender'], df['Department']],
    df['Experience'] > 3,
    normalize='index'
)

Experience         False  True
Gender Department
F      HR            0.5    0.5
       IT            0.0    1.0
       Sales         1.0    0.0
M      HR            1.0    0.0
       IT            0.5    0.5
       Sales         1.0    0.0

In [24]:
df = pd.read_excel(r"C:\Users\masir\Downloads\survey.xls")
df

      Name Nationality     Sex  Age Handedness
0    Kathy         USA  Female   23      Right
1    Linda         USA  Female   18      Right
2    Peter         USA    Male   19      Right
3     John         USA    Male   22       Left
4   Fatima   Bangadesh  Female   31       Left
5    Kadir   Bangadesh    Male   25       Left
6   Dhaval       India    Male   35       Left
7   Sudhir       India    Male   31       Left
8   Parvir       India    Male   37      Right
9      Yan       China  Female   52      Right
10    Juan       China  Female   58       Left
11   Liang       China    Male   43       Left

In [37]:
g=df.groupby('Nationality')
for i,j in g:
    print(i,j,sep='\n')

Bangadesh
     Name Nationality     Sex  Age Handedness
4  Fatima   Bangadesh  Female   31       Left
5   Kadir   Bangadesh    Male   25       Left
China
     Name Nationality     Sex  Age Handedness
9     Yan       China  Female   52      Right
10   Juan       China  Female   58       Left
11  Liang       China    Male   43       Left
India
     Name Nationality   Sex  Age Handedness
6  Dhaval       India  Male   35       Left
7  Sudhir       India  Male   31       Left
8  Parvir       India  Male   37      Right
USA
    Name Nationality     Sex  Age Handedness
0  Kathy         USA  Female   23      Right
1  Linda         USA  Female   18      Right
2  Peter         USA    Male   19      Right
3   John         USA    Male   22       Left

In [25]:
pd.crosstab(df.Nationality,df.Handedness)

Handedness   Left  Right
Nationality
Bangadesh       2      0
China           2      1
India           2      1
USA             1      3

In [27]:
pd.crosstab(df['Sex'],df['Handedness'],margins=True)

Handedness  Left  Right  All
Sex
Female         2      3    5
Male           5      2    7
All            7      5   12

In [28]:
pd.crosstab([df['Nationality'],df['Sex']],df['Handedness'],margins=True)

Handedness          Left  Right  All
Nationality Sex
Bangadesh   Female     1      0    1
            Male       1      0    1
China       Female     1      1    2
            Male       1      0    1
India       Male       2      1    3
USA         Female     0      2    2
            Male       1      1    2
All                    7      5   12

In [30]:
pd.crosstab([df['Nationality'],df['Sex'],df['Name']],df['Handedness'],margins=True)

Handedness                 Left  Right  All
Nationality Sex    Name
Bangadesh   Female Fatima     1      0    1
            Male   Kadir      1      0    1
China       Female Juan       1      0    1
                   Yan        0      1    1
            Male   Liang      1      0    1
India       Male   Dhaval     1      0    1
                   Parvir     0      1    1
                   Sudhir     1      0    1
USA         Female Kathy      0      1    1
                   Linda      0      1    1
            Male   John       1      0    1
                   Peter      0      1    1
All                           7      5   12

In [34]:
pd.crosstab([df['Nationality'],df['Sex'][df['Sex']=='Female']],df['Handedness'],margins=True,values=df.Age,aggfunc='mean')
# Bangadesh
#      Name Nationality     Sex  Age Handedness
# 4  Fatima   Bangadesh  Female   31       Left
# 5   Kadir   Bangadesh    Male   25       Left
# China
#      Name Nationality     Sex  Age Handedness
# 9     Yan       China  Female   52      Right
# 10   Juan       China  Female   58       Left
# 11  Liang       China    Male   43       Left
# India
#      Name Nationality   Sex  Age Handedness
# 6  Dhaval       India  Male   35       Left
# 7  Sudhir       India  Male   31       Left
# 8  Parvir       India  Male   37      Right
# USA
#     Name Nationality     Sex  Age Handedness
# 0  Kathy         USA  Female   23      Right
# 1  Linda         USA  Female   18      Right
# 2  Peter         USA    Male   19      Right

Handedness          Left  Right   All
Nationality Sex
Bangadesh   Female  31.0    NaN  31.0
China       Female  58.0   52.0  55.0
USA         Female   NaN   20.5  20.5
All                 44.5   31.0  36.4

# pivot() and pivot_table()

In [60]:
data = {
    'date': ['5/1/2017','5/2/2017','5/3/2017',
             '5/1/2017','5/2/2017','5/3/2017',
             '5/1/2017','5/2/2017','5/3/2017'],
    'city': ['new york','new york','new york',
             'mumbai','mumbai','mumbai',
             'beijing','beijing','beijing'],
    'temperature': [65,66,68,75,78,82,80,77,79],
    'humidity': [56,58,60,80,83,85,26,30,35]
}

weather = pd.DataFrame(data)

In [61]:
data = {
    'date': ['5/1/2017', '5/1/2017', '5/2/2017', '5/2/2017',
             '5/1/2017', '5/1/2017', '5/2/2017', '5/2/2017'],
    'city': ['new york', 'new york', 'new york', 'new york',
             'mumbai', 'mumbai', 'mumbai', 'mumbai'],
    'temperature': [65, 61, 70, 72, 75, 78, 82, 80],
    'humidity': [56, 54, 60, 62, 80, 83, 85, 26]
}

weather2 = pd.DataFrame(data)

In [62]:
data = {
    'date': ['5/1/2017', '5/2/2017', '5/3/2017',
             '12/1/2017', '12/2/2017', '12/3/2017'],
    'city': ['new york', 'new york', 'new york',
             'new york', 'new york', 'new york'],
    'temperature': [65, 61, 70, 30, 28, 25],
    'humidity': [56, 54, 60, 50, 52, 51]
}
weather3 = pd.DataFrame(data)

In [63]:
weather

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

In [64]:
weather.pivot(index='date',columns='city')

         temperature                 humidity
city         beijing mumbai new york  beijing mumbai new york
date
5/1/2017          80     75       65       26     80       56
5/2/2017          77     78       66       30     83       58
5/3/2017          79     82       68       35     85       60

In [65]:
weather.pivot(index='date',columns='city',values='humidity')

city      beijing  mumbai  new york
date
5/1/2017       26      80        56
5/2/2017       30      83        58
5/3/2017       35      85        60

In [66]:
weather.pivot(index='humidity',columns='city')

              date                     temperature
city       beijing    mumbai  new york     beijing mumbai new york
humidity
26        5/1/2017       NaN       NaN        80.0    NaN      NaN
30        5/2/2017       NaN       NaN        77.0    NaN      NaN
35        5/3/2017       NaN       NaN        79.0    NaN      NaN
56             NaN       NaN  5/1/2017         NaN    NaN     65.0
58             NaN       NaN  5/2/2017         NaN    NaN     66.0
60             NaN       NaN  5/3/2017         NaN    NaN     68.0
80             NaN  5/1/2017       NaN         NaN   75.0      NaN
83             NaN  5/2/2017       NaN         NaN   78.0      NaN
85             NaN  5/3/2017       NaN         NaN   82.0      NaN

In [67]:
weather2

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           80        26

In [77]:
weather2.pivot_table(index='city',columns='date')
# default aggregate function is mean

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai       81.5     55.5        76.5     81.0
new york     55.0     61.0        63.0     71.0

In [78]:
weather2.pivot_table(index='city',columns='date',aggfunc=['sum','count'],margins=True)

              sum                                            count           \
         humidity               temperature               humidity
date     5/1/2017 5/2/2017  All    5/1/2017 5/2/2017  All 5/1/2017 5/2/2017
city
mumbai        163      111  274         153      162  315        2        2
new york      110      122  232         126      142  268        2        2
All           273      233  506         279      304  583        4        4


             temperature
date     All    5/1/2017 5/2/2017 All
city
mumbai     4           2        2   4
new york   4           2        2   4
All        8           4        4   8

In [85]:
weather3

        date      city  temperature  humidity
0 2017-05-01  new york           65        56
1 2017-05-02  new york           61        54
2 2017-05-03  new york           70        60
3 2017-12-01  new york           30        50
4 2017-12-02  new york           28        52
5 2017-12-03  new york           25        51

In [83]:
weather3['date']=pd.to_datetime(weather3['date'])

In [86]:
weather3.pivot_table(index=pd.Grouper(freq='M',key='date'),columns='city')

C:\Users\masir\AppData\Local\Temp\ipykernel_14152\3090464305.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  weather3.pivot_table(index=pd.Grouper(freq='M',key='date'),columns='city')

             humidity temperature
city         new york    new york
date
2017-05-31  56.666667   65.333333
2017-12-31  51.000000   27.666667

In [88]:
df = pd.DataFrame({
    'Date': ['Jan', 'Jan', 'Feb', 'Feb'],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Mumbai'],
    'Temp': [30, 35, 32, 36]
})
df

  Date    City  Temp
0  Jan   Delhi    30
1  Jan  Mumbai    35
2  Feb   Delhi    32
3  Feb  Mumbai    36

In [89]:
print(df.pivot(index='Date', columns='City', values='Temp'))

City  Delhi  Mumbai
Date
Feb      32      36
Jan      30      35

In [90]:
df = pd.DataFrame({
    'Day': ['Mon', 'Mon', 'Tue', 'Tue'],
    'Subject': ['Math', 'Sci', 'Math', 'Sci'],
    'Marks': [90, 85, 88, 82]
})
df.pivot(index='Day', columns='Subject', values='Marks')

Subject  Math  Sci
Day
Mon        90   85
Tue        88   82

In [98]:
df = pd.DataFrame({
    'City': ['A', 'A', 'B', 'B'],
    'Year': [2020, 2021, 2020, 2021],
    'Sales': [100, 120, 90, 110]
})
print(df)
result = df.pivot(index='City', columns='Year', values='Sales').reset_index()
result

  City  Year  Sales
0    A  2020    100
1    A  2021    120
2    B  2020     90
3    B  2021    110

Year City  2020  2021
0       A   100   120
1       B    90   110

In [99]:
df = pd.DataFrame({
    'City': ['A', 'A'],
    'Year': [2020, 2020],
    'Sales': [100, 200]
})
# ❌ This will raise error because duplicate ('A',2020)
df.pivot(index='City', columns='Year', values='Sales')

ValueError: Index contains duplicate entries, cannot reshape

In [100]:
df.pivot_table(index='City', columns='Year', values='Sales', aggfunc='sum')

Year  2020
City
A      300

In [101]:
df = pd.DataFrame({
    'Region': ['North', 'North', 'South', 'South'],
    'City': ['Delhi', 'Delhi', 'Chennai', 'Chennai'],
    'Year': [2020, 2021, 2020, 2021],
    'Sales': [100, 120, 80, 95]
})

pivoted = df.pivot(index=['Region', 'City'], columns='Year', values='Sales')
print(pivoted)

Year            2020  2021
Region City
North  Delhi     100   120
South  Chennai    80    95

In [103]:

df = pd.DataFrame({
    'City': ['Delhi', 'Delhi', 'Mumbai', 'Mumbai'],
    'Year': [2020, 2020, 2020, 2021],
    'Sales': [100, 150, 200, 300]
})

result = df.pivot_table(index='City', columns='Year', values='Sales', aggfunc='sum')
print(result)

Year     2020   2021
City
Delhi   250.0    NaN
Mumbai  200.0  300.0

In [104]:
df = pd.DataFrame({
    'City': ['A', 'A', 'B', 'B'],
    'Year': [2020, 2020, 2020, 2021],
    'Sales': [100, 200, 150, 300]
})
df.pivot_table(index='City', columns='Year', values='Sales', aggfunc='sum')

Year   2020   2021
City
A     300.0    NaN
B     150.0  300.0

In [105]:
df = pd.DataFrame({
    'City': ['A', 'A', 'B', 'B'],
    'Year': [2020, 2020, 2021, 2021],
    'Sales': [100, 150, 200, 250],
    'Profit': [10, 15, 20, 25]
})

result = df.pivot_table(
    index='City',
    columns='Year',
    values=['Sales', 'Profit'],
    aggfunc='sum'
)
print(result)

     Profit        Sales
Year   2020  2021   2020   2021
City
A      25.0   NaN  250.0    NaN
B       NaN  45.0    NaN  450.0

In [106]:
df = pd.DataFrame({
    'City': ['A', 'A', 'B', 'B'],
    'Year': [2020, 2021, 2020, 2021],
    'Sales': [100, 200, 150, 300]
})

result = df.pivot_table(
    index='City',
    columns='Year',
    values='Sales',
    aggfunc='sum',
    fill_value=0,
    margins=True  
)
print(result)

Year  2020  2021  All
City
A      100   200  300
B      150   300  450
All    250   500  750

In [107]:
df = pd.DataFrame({
    'Region': ['North', 'North', 'South', 'South'],
    'City': ['Delhi', 'Delhi', 'Chennai', 'Chennai'],
    'Year': [2020, 2021, 2020, 2021],
    'Sales': [100, 120, 90, 95]
})

result = df.pivot_table(
    index=['Region', 'City'],
    columns='Year',
    values='Sales',
    aggfunc='sum'
)
print(result)

Year            2020  2021
Region City
North  Delhi     100   120
South  Chennai    90    95